SET NAMES UTF8;
DROP DATABASE IF EXISTS travelV;
CREATE DATABASE travelV CHARSET=UTF8;
USE travelV;
/*创建用户表*/
CREATE TABLE traV_user(
  usid INT PRIMARY KEY AUTO_INCREMENT,
  t_name VARCHAR(64),
  t_phone VARCHAR(11),
  t_password VARCHAR(32),
  isLogin INT
);
INSERT INTO traV_user VALUE('1',"dingding","13689567895","123456789",0);

/*首页中轮播图的数据*/
CREATE TABLE traV_indexBanner(
  ibid INT PRIMARY KEY AUTO_INCREMENT,
  ib_pic VARCHAR(256),
  id_title VARCHAR(128),
  id_detail VARCHAR(256)
);
INSERT INTO traV_indexBanner VALUES
(NULL,"img/index/banner1.jpg","穷游锦囊 | 玻利维亚","1行走于天空之镜，徜徉于高原圣湖，开启一次奔向原始自然的回归之旅"),
(NULL,"img/index/banner2.jpg","【尼泊尔游记攻略】尼泊尔安娜普尔纳大环线徒步","versemonger"),
(NULL,"img/index/banner3.jpg","【墨西哥&古巴游记攻略】属于墨西哥+古巴的春节13日亲子时光","peper_key"),
(NULL,"img/index/banner4.jpg","【穷游专栏】Dou桑的摄影旅行｜洛杉矶滑板圣地巡礼","Doozee"),
(NULL,"img/index/banner5.jpg","【日本游记攻略】世间若无樱花艳，春心何处得长闲","Ken_leung");
/*今日推荐表*/
CREATE TABLE traV_todayRecommend(
  reid INT PRIMARY KEY AUTO_INCREMENT,
  re_icon VARCHAR(32),
  re_source_audio VARCHAR(256),
  re_title VARCHAR(128),
  re_leftinfo VARCHAR(128),
  re_rightinfo VARCHAR(128),
  re_price DECIMAL(8,2) 
);
INSERT INTO traV_todayRecommend VALUES
(NULL,"视频","img/index/recommed/recommd1.mp4","和牛汉堡vs袋鼠肉，哪个更美味？","旅行囧记","凯恩斯",""),
(NULL,"商城","img/index/recommed/recommd2.png","[暑期]成都/重庆直飞清迈5-6天往返含税机票(包机航班+可代办签证+可自由搭配酒店自由行)","成都,重庆","元起","888"),
(NULL,"游记","img/index/recommed/recommd3.jpg","#旅途影像#风情法兰西（内附机位分享）","Catshenyimin","10111人浏览过",""),
(NULL,"商城","img/index/recommed/recommd4.png","[暑期特惠]广州/深圳/中山/东莞往返东京/大阪5-16天往返含税机票（赠送各地码头往返香港船票+可缺口行程）","广东","元起","2999"),
(NULL,"商城","img/index/recommed/recommd5.jpg","[暑期]广州直飞泰国甲米6天4晚自由行（川航直飞+精选4晚星级酒店含早+赠接送机服务+泰国落地签限时免费）","广州","元起","1999"),
(NULL,"专栏","img/index/recommed/recommd6.png","带你一路探索苏格兰秘境斯凯岛","熊和考拉走天涯","lyandkoala",""),
(NULL,"游记","img/index/recommed/recommd7.jpg","不可思议之五彩印度","橙小橙橙走天涯","1795人浏览过",""),
(NULL,"游记","img/index/recommed/recommd8.jpg","从笼潜到蹦极丨一路向南非去不可（45天的深度冒险）","双喜与子琛","6640人浏览过","");

/*index中商城的表格*/
CREATE TABLE traV_indexMall(
  pid INT PRIMARY KEY AUTO_INCREMENT,
  clid INT, /*商品类别分类，路线1，游轮2，景点3*/
  ma_thumPic VARCHAR(256),
  ma_title VARCHAR(256),
  ma_active VARCHAR(128),
  ma_price DECIMAL(8,2),
  ma_timeFinish VARCHAR(16)
);
INSERT INTO traV_indexMall VALUES
(NULL,"1","img/index/mall/pid1.jpg","上海直飞缅甸5-7天自由行（走进大小S综艺拍摄地+体验一个淳朴有信仰的国度+品质酒店住宿可选+提前一个月预订热气球）","APP立减600元","2899","2"),
(NULL,"2","img/index/mall/pid2.jpg","[08月23日]星梦邮轮探索梦号天津往返福冈市5天4晚邮轮之旅","APP立减600元","2399","64"),
(NULL,"2","img/index/mall/pid3.jpg","上海/南京/无锡/合肥往返马来西亚沙巴+仙本那6-7天自由行（海风拂面·多地出发+DIY行程设计+玩点新鲜的+高度自由+不走寻常路+享受你的假期）","APP立减600元","4080","64"),
(NULL,"3","img/index/mall/pid4.jpg","日本大阪周游卡OSAKA AMAZINGPASS(1日/2日券)","秒杀","168",""),
(NULL,"3","img/index/mall/pid5.jpg","[上下午通用]北京故宫门票/联票(可选含钟表馆、珍宝馆）","秒杀","20",""),
(NULL,"3","img/index/mall/pid6.jpg","上海迪士尼乐园","秒杀","279","");

/*首页游记和话题*/
CREATE TABLE traV_indexTravelNote(
  tnid INT PRIMARY KEY AUTO_INCREMENT,
  tn_lapic VARCHAR(256),
  tn_headPic VARCHAR(256),
  tn_authorName VARCHAR(64),
  tn_isGreat VARCHAR(32),
  tn_noteTitle VARCHAR(256),
  tn_commentCount INT
);
INSERT INTO traV_indexTravelNote VALUES
(NULL,"img/index/travel_note/tn1.jpg","img/index/travel_note/tns1.jpg","Risa不在家","精华","【曼谷】非大众丰富玩法--市内及周边各种走心推荐！（多图、含自由行攻略）","3"),
(NULL,"img/index/travel_note/tn2.jpg","img/index/travel_note/tns2.jpg","姗姗来迟310","精华","落叶有声——记录行走在德国和捷克（柏林、德累斯顿、布拉格）的八天，含德铁DB购票、国会大厦预订、柏林爱乐预订等。","325"),
(NULL,"img/index/travel_note/tn3.jpg","img/index/travel_note/tns3.jpg","周若雪Patty_","精华","旅行|海鲜、日落游艇、撸猫，解锁不一样的美国热带风情！","12"),
(NULL,"img/index/travel_note/tn4.jpg","img/index/travel_note/tns4.jpg","小肉团很折腾","精华","7天9夜尼泊尔 | 身披纱丽，漫步众神的国度","55"),
(NULL,"img/index/travel_note/tn5.jpg","img/index/travel_note/tns5.jpg","谢旭","精华","探险马达加斯加：从原始到文明的蜕变（山人游记26）","44"),
(NULL,"img/index/travel_note/tn6.jpg","img/index/travel_note/tns6.jpg","小四喜子","精华","新西兰南岛14天，新婚的我们和牛奶蓝的梦（超多美图、超详细手机摄影技巧、自驾/景点/穷游攻略）","67"),
(NULL,"img/index/travel_note/tn7.jpg","img/index/travel_note/tns7.jpg","红狐在天","精华","日本九州JR铁路全攻略，手把手教你搞定全九州特色铁路之旅","27"),
(NULL,"img/index/travel_note/tn8.jpg","img/index/travel_note/tns8.jpg","ThisIsHang","精华","目的地荷兰 郁金香风车运河的国度 (Holland Pass通票攻略)","107"),
(NULL,"img/index/travel_note/tn21.jpg","img/index/travel_note/tns21.jpg","舒利文","精华","暴走挑战|每天只睡5小时的泰国清迈五一行全纪录","37"),
(NULL,"img/index/travel_note/tn22.jpg","img/index/travel_note/tns22.jpg","锦儿Amy","精华","完结!【小宇环球旅行之1.5岁】不去仙本娜也精彩，扶老携幼沙巴7日全攻略（沙比岛、美人鱼岛、天空之镜）签证步骤、带娃攻略","103"),
(NULL,"img/index/travel_note/tn23.jpg","img/index/travel_note/tns23.jpg","曲曲小姐","精华","雨季锡兰，独享自由（1人2国12城16天公共交通玩转斯里兰卡）","22"),
(NULL,"img/index/travel_note/tn24.png","img/index/travel_note/tns24.jpg","Ginojo","","[葡萄牙]DJI小残手经验分享+自驾游玩攻略","156"),
(NULL,"img/index/travel_note/tn25.jpg","img/index/travel_note/tns25.jpg","自由的鱼","精华","不丹，幸福最好的诠释-2019年我在不丹的7天（详细攻略+游记+美图+视频）","147"),
(NULL,"img/index/travel_note/tn26.jpg","img/index/travel_note/tns26.jpg","小小小艾琳","精华","我可能很爱你之新年新旅程——2019新加坡跨年记（独家HPV疫苗攻略！美食美景都不辜负，全文更完）","8"),
(NULL,"img/index/travel_note/tn27.jpg","img/index/travel_note/tns27.jpg","小叶子DE买买提","精华","【小叶子DE买买提】收进记忆里的深秋（列支敦士登+瑞士）","55"),
(NULL,"img/index/travel_note/tn28.jpg","img/index/travel_note/tns28.jpg","Ms小蕾西","精华","春假里遇见打开快乐的100种方式 --- 一家三口去首尔 快乐就是互相牵手呀","10"),
(NULL,"img/index/travel_note/tn31.jpg","img/index/travel_note/tns31.jpg","Troy_Xu","精华","【度假圣地汉密尔顿岛】浪漫大堡礁门户，圣灵群岛攻略（海量美图+上帝视角+详细攻略）","17"),
(NULL,"img/index/travel_note/tn32.jpg","img/index/travel_note/tns32.jpg","邹雯艾","精华","来~!让我跟你聊聊新加坡的秘境小众美景","41"),
(NULL,"img/index/travel_note/tn33.jpg","img/index/travel_note/tns33.jpg","背包客南迦巴瓦","精华","独行印度，探秘德里金三角的世界遗产（八万字六百图）","61"),
(NULL,"img/index/travel_note/tn34.jpg","img/index/travel_note/tns34.jpg","嘎兰","精华","以色列：你许给了我一个未来","21"),
(NULL,"img/index/travel_note/tn35.jpg","img/index/travel_note/tns35.jpg","辰辰-chenchen","精华","♕♔你要的房车自驾游tips 这里通通都有♚♛ 驾驶移动城堡，房车畅游法瑞德奥意","39"),
(NULL,"img/index/travel_note/tn36.jpg","img/index/travel_note/tns36.jpg","tango炭哥","","致敬苍茫的西伯利亚大地，融入贝加尔湖的深蓝","3"),
(NULL,"img/index/travel_note/tn37.jpg","img/index/travel_note/tns37.jpg","麻小薯","精华","你有一份澳门美食地图待查收，三天吃遍小澳门的秘诀就在这『更新KLOOK体验』","5"),
(NULL,"img/index/travel_note/tn38.png","img/index/travel_note/tns38.jpg","aero4400","精华","【AERO4400】美国小众：探纳什维尔乡村音乐，追大烟山梦幻萤火虫（附萤火虫抽签／不抽签攻略及拍摄技巧，小众印第安村）","36"),
(NULL,"img/index/travel_note/tn41.jpg","img/index/travel_note/tns41.jpg","Nico出品","精华","意大利•印象——意大利半岛全景三国纪实+自驾经验（已完结）","23"),
(NULL,"img/index/travel_note/tn42.jpg","img/index/travel_note/tns42.jpg","抱衾听雪","","花甲阿姨暴走伦敦，绿色出行赢在体力","183"),
(NULL,"img/index/travel_note/tn43.jpg","img/index/travel_note/tns43.jpg","peper_key","精华","就是想带你去看世界-属于墨西哥+古巴的春节13日亲子时光，超全干货（瓜纳华托就医，哈瓦那游乐园经历）【完结】","172"),
(NULL,"img/index/travel_note/tn44.jpg","img/index/travel_note/tns44.jpg","EolandeRong","精华","【小芒果酱亲子游记】陪你看世界之四世同游台湾（半环岛亲子游：附详细订台铁亲子票、为八旬外婆租轮椅、HPV疫苗攻略）","156"),
(NULL,"img/index/travel_note/tn45.jpg","img/index/travel_note/tns45.jpg","小词词","","探索BC省，一场“风花雪月”的自驾旅行，在湖光山色和饕餮美食里沉醉","16"),
(NULL,"img/index/travel_note/tn46.jpg","img/index/travel_note/tns46.jpg","花椰菜007","精华","海外游之初体验-清迈拜县闺蜜悠游记","96"),
(NULL,"img/index/travel_note/tn47.jpg","img/index/travel_note/tns47.jpg","精壮的小南僧","精华","摩洛哥自由行攻略（卡萨布兰卡/舍夫沙万/菲斯/撒哈拉/马拉喀什）12日全记录","12"),
(NULL,"img/index/travel_note/tn48.jpg","img/index/travel_note/tns48.jpg","掰二雷","","唱一首秋的颂歌｜26岁尾声带着不一样的身份重返新西兰","36"),
(NULL,"img/index/travel_note/tn51.jpg","img/index/travel_note/tns51.jpg","月神侠","精华","一岛，一城，一山，一湖-5月12-5月19日冲绳东京河口湖8日游","42"),
(NULL,"img/index/travel_note/tn52.jpg","img/index/travel_note/tns52.jpg","安哲_ran","精华","【一个人的旅行】自带时光机的非典型缅甸","26"),
(NULL,"img/index/travel_note/tn53.jpg","img/index/travel_note/tns53.jpg","sarixuan","精华","心有巴厘千千结（小长假玩转巴厘岛行摄笔记）","0"),
(NULL,"img/index/travel_note/tn54.jpg","img/index/travel_note/tns54.jpg","逆光行纪","精华","【逆光航海】印度洋单身生存指南|与海洋光谱号重走香料之路","16"),
(NULL,"img/index/travel_note/tn55.jpg","img/index/travel_note/tns55.jpg","奶糖人7号","精华","[奶糖出品]荷兰+比利时9日寻花问画漫行记|库肯霍夫/羊角村/小孩堤防/德哈尔城堡/梵高夜光路（实用攻略+千图游记）","90"),
(NULL,"img/index/travel_note/tn56.jpg","img/index/travel_note/tns56.jpg","Hino_Amane","精华","在北京办理蒙古签证报告 2019/06/17","7"),
(NULL,"img/index/travel_note/tn57.jpg","img/index/travel_note/tns57.jpg","夕月冉冉","精华","(完更）像当地人一样游玩——2018年夏一家三口浪在中欧30日（德荷匈奥捷5国，看山看水看博物馆，看不够的城市与山野）","68"),
(NULL,"img/index/travel_note/tn58.jpg","img/index/travel_note/tns58.jpg","爱溜达的猫","精华","南纬18度的避世秘境--瓦努阿图","109");

/*首页中穷游体验馆的数据*/
CREATE TABLE traV_experience(
  eid INT PRIMARY KEY AUTO_INCREMENT,
  ex_lapic VARCHAR(256),
  ex_hpic1 VARCHAR(256),
  ex_hpic2 VARCHAR(256),
  ex_hpic3 VARCHAR(256),
  ex_hpic4 VARCHAR(256),
  ex_hpic5 VARCHAR(256),
  ex_hpic6 VARCHAR(256),
  ex_hpic7 VARCHAR(256),
  ex_hpic8 VARCHAR(256),
  ex_hpic9 VARCHAR(256),
  ex_hpic10 VARCHAR(256),
  ex_title VARCHAR(128),
  ex_price DECIMAL(8,2),
  ex_freecount INT,
  ex_isfinish VARCHAR(64)
);
INSERT INTO traV_experience VALUE(NULL,"img/index/floor4/raw.jpg","img/index/floor4/head1.jpg","img/index/floor4/head2.jpg","img/index/floor4/head3.jpg","img/index/floor4/head4.jpg","img/index/floor4/head5.jpg","img/index/floor4/head6.jpg","img/index/floor4/head7.jpg","img/index/floor4/head8.jpg","img/index/floor4/head9.jpg","img/index/floor4/head10.jpg","穿越时空的旅行者 猫王旅行体验官招募","499","20","申请已结束");

/*首页中特别策划的样式*/
CREATE TABLE traV_plan(
  plid INT PRIMARY KEY AUTO_INCREMENT,
  pl_theme VARCHAR(64),
  pl_orcodepic VARCHAR(256),
  pl_pic VARCHAR(256),
  pl_phonepic VARCHAR(256),
  pl_phonesepic VARCHAR(256)
);
INSERT INTO traV_plan VALUES
(NULL,"三天两夜","img/index/floor4/orcode1.png","img/index/floor4/feel1.png","img/index/floor4/phone.png","img/index/floor4/phonese.png"),
(NULL,"上瘾团","","img/index/floor4/feel2.png","",""),
(NULL,"三天两夜","img/index/floor4/orcode3.png","img/index/floor4/feel3.png","img/index/floor4/phone.png","img/index/floor4/phonese.png"),
(NULL,"地球研究社","img/index/floor4/orcode4.png","img/index/floor4/feel4.png","img/index/floor4/phone.png","img/index/floor4/phonese.png"),
(NULL,"上瘾团","","img/index/floor4/feel5.png","","");


/*国家分类*/
CREATE TABLE traV_country_classify(
  country_clid INT PRIMARY KEY AUTO_INCREMENT,
  country_clname VARCHAR(32)
);
INSERT INTO traV_country_classify VALUES
(NULL,"热门推荐"),
(NULL,"日韩及港澳台"),
(NULL,"东南亚及亚洲其他"),
(NULL,"欧洲"),
(NULL,"大洋洲及北美"),
(NULL,"非洲及南美");

/*城市分类推荐*/
CREATE TABLE traV_city_classigy(
  city_clid INT PRIMARY KEY AUTO_INCREMENT,
  country_clid INT,
  country_ciname VARCHAR(64),
  citys_name VARCHAR(512)
);
INSERT INTO traV_city_classigy VALUES
(NULL,"1","全球top 10城市",'["东京","曼谷","香港","台北","新加坡","巴黎","罗马","伦敦","首尔","洛杉矶"]'),
(NULL,"1","免签及落地签最热旅行地",'["济州岛","印度尼西亚","泰国","塞班岛","摩洛哥","卡塔尔","毛里求斯","柬埔寨","厄瓜多尔",]'),
(NULL,"1","热门海岛",'["塞班岛","长滩岛","马尔代夫","沙巴","普吉岛","巴厘岛","芽庄","帕劳","冲绳市"]'),
(NULL,"2","港澳台",'["香港","澳门","台北","垦丁","花莲","高雄市","台中市","九份","台南","淡水","宜兰"]'),
(NULL,"2","日本","['东京','大阪','京都','冲绳','北海道','名古屋','奈良','札幌','富士山地区', '箱根','镰仓','神户']"),
(NULL,"2","韩国","['首尔','济州岛','釜山']"),
(NULL,"3","泰国","['曼谷','普吉岛','清迈','苏梅岛','芭提雅','甲米','华欣','皮皮岛','泰国象岛','拜县']"),
(NULL,"3","新加坡","['新加坡']"),
(NULL,"3","越南","['芽庄','岘港','胡志明市','河内','美奈','大叻','富国岛']"),
(NULL,"3","马来西亚","['沙巴','吉隆坡','槟城','亚庇','兰卡威','马六甲','仙本那']"),
(NULL,"3","印度尼西亚","['巴厘岛','美娜多','乌布']"),
(NULL,"3","菲律宾","['长滩岛','马尼拉','薄荷岛','杜马盖地','宿雾市']"),
(NULL,"3","斯里兰卡","['科伦坡','斯里兰卡康堤']"),
(NULL,"3","柬埔寨","['暹粒','金边']"),
(NULL,"3","亚洲其他","['迪拜','马尔代夫','阿布扎比','耶路撒冷','基什岛','加德满都','德里','仰光','多哈']"),
(NULL,"4","意大利","['罗马','佛罗伦萨','威尼斯','米兰','五渔村','那不勒斯','西西里岛','比萨','维罗纳','锡耶纳']"),
(NULL,"4","英国","['伦敦','爱丁堡','剑桥','牛津','英国湖区','曼彻斯特','巴斯','约克','苏格兰']"),
(NULL,"4","德国","['慕尼黑','法兰克福','柏林','科隆','海德堡','汉堡','斯图加特','杜塞尔多夫','纽伦堡','德累斯顿']"),
(NULL,"4","法国","['巴黎','尼斯','普罗旺斯','阿维尼翁','里昂','马赛','波尔多','斯特拉斯堡','戛纳']"),
(NULL,"4","西班牙","['巴塞罗那','马德里','塞维利亚','格拉纳达','瓦伦西亚','托莱多','龙达','马略卡岛']"),
(NULL,"4","瑞士","['苏黎世','卢塞恩','因特拉肯','日内瓦','伯尔尼','洛桑']"),
(NULL,"4","奥地利","['维也纳','萨尔茨堡','哈尔施塔特','因斯布鲁克']"),
(NULL,"4","俄罗斯","['莫斯科','贝加尔湖','圣彼得堡','伊尔库茨克','符拉迪沃斯托克(海参崴)']"),
(NULL,"4","捷克","['布拉格','捷克克鲁姆洛夫']"),
(NULL,"4","荷兰","['阿姆斯特丹','羊角村','鹿特丹','海牙']"),
(NULL,"4","希腊","['圣托里尼','雅典','克里特岛','米科诺斯岛']"),
(NULL,"5","澳大利亚","['墨尔本','悉尼','黄金海岸','布里斯班','凯恩斯','珀斯','塔斯马尼亚岛','阿德莱德','袋鼠岛']"),
(NULL,"5","新西兰","['奥克兰','皇后镇','基督城','新西兰南岛']"),
(NULL,"5","美国","['洛杉矶','纽约','塞班岛','旧金山','拉斯维加斯','加州圣地亚哥','波士顿','华盛顿','黄石国家公园','夏威夷','西雅图','关岛']"),
(NULL,"5","加拿大","['温哥华','班夫国家公园','多伦多','蒙特利尔','加拿大尼亚加拉瀑布城']"),
(NULL,"5","其他","['帕劳','坎昆','墨西哥城','哈瓦那']"),
(NULL,"6","摩洛哥","['卡萨布兰卡','马拉喀什','菲斯','舍夫沙万']"),
(NULL,"6","埃及","['开罗','卢克索']"),
(NULL,"6","南非","['开普敦','约翰内斯堡']"),
(NULL,"6","肯尼亚","['内罗毕','马赛马拉国家保护区']"),
(NULL,"6","秘鲁","['马丘比丘','利马']"),
(NULL,"6","阿根廷","['布宜诺斯艾利斯','乌斯怀亚','埃尔卡拉法特']"),
(NULL,"6","毛里求斯","['毛里求斯']"),
(NULL,"6","智利","['圣地亚哥','复活节岛']"),
(NULL,"6","巴西","['里约热内卢','圣保罗','巴西萨尔瓦多']"),
(NULL,"6","玻利维亚","['乌尤尼','拉巴斯']"),
(NULL,"6","厄瓜多尔","['加拉帕戈斯群岛','基多','瓜亚基尔']");


/*主题目的地表*/
CREATE TABLE traV_theme_part(
  th_classify_id INT PRIMARY KEY AUTO_INCREMENT,
  th_classify_name VARCHAR(64)
);
INSERT INTO traV_theme_part VALUES
(NULL,"俯瞰城市"),
(NULL,"怀旧时光"),
(NULL,"魅力夜色"),
(NULL,"神秘遗址"),
(NULL,"最爱小镇");
CREATE TABLE traV_theme_partinfo(
  th_id INT PRIMARY KEY AUTO_INCREMENT,
  th_classify_id INT,
  th_pic VARCHAR(256),
  th_title VARCHAR(256),
  th_detail_info VARCHAR(512)
);
INSERT INTO traV_theme_partinfo VALUES
(NULL,1,"img/destination/theme11.jpg","洛克菲勒观景台","这里是欣赏曼哈顿天际线的绝佳位置，观景台一共有三层，不仅可以将帝国大厦、新世贸中心大楼等摩天大楼尽收眼底，向北可鸟瞰中央公园，甚至可以看到自由女神像的绰约风姿"),
(NULL,1,"img/destination/theme12.png","碎片大厦","天气晴朗的日子里，在碎片大厦观景台可以将伦敦市景一收眼底，伦敦眼、大本钟、泰晤士河……只描摹出城市轮廓的夕阳景色更是出众。"),
(NULL,1,"img/destination/theme13.jpg","太平山","太平山是香港岛最高山峰，也是俯瞰香港的必到处，太平山顶可饱览维多利亚港全貌和薄扶林水塘的自然美景。"),
(NULL,1,"img/destination/theme14.png","六本木新城","六本木Hills建成于2003年，54层楼的玻璃大厦内有200多家店铺，餐饮、购物、娱乐一应俱全，很多日本人将它当做六本木的代名词。"),
(NULL,1,"img/destination/theme15.jpg","米开朗琪罗广场","米开朗基罗广场位于佛罗伦萨市区南端的高地上，广场雄据半山腰，坐视整个佛罗伦萨城及远处起伏不断的丘陵，气势非凡，风光无限。"),
(NULL,1,"img/destination/theme16.png","象山","山不高，但前无屏障，台北盆地一览无遗，不仅是登高眺望的好据点，也是拍摄101高楼的绝佳地点"),
(NULL,1,"img/destination/theme17.jpg","蒙帕纳斯大楼","蒙帕纳斯大楼(又称蒙巴纳斯高楼)建于1972年，共59层，高209米，是巴黎市区除埃菲尔铁塔外最高的建筑，也是市区唯一的一座摩天大楼。"),
(NULL,2,"img/destination/theme21.jpg","京都","春樱秋枫，神社古庙，古道旁，再现平安时代的风华盛景。"),
(NULL,2,"img/destination/theme22.jpg","亚兹德","丝绸之路途中的千年驿站，沙漠中的古城。"),
(NULL,2,"img/destination/theme23.jpg","马丘比丘","神秘的印加帝国遗迹。"),
(NULL,2,"img/destination/theme24.jpg","蒲甘","千塔之城，每一座佛塔都是一段时光的记忆。"),
(NULL,2,"img/destination/theme25.jpg","马六甲","追寻郑和的足迹。"),
(NULL,2,"img/destination/theme26.jpg","罗滕堡","保存完好的中世纪风貌，保存完好的德国浪漫之路。"),
(NULL,2,"img/destination/theme27.jpg","庆州","新罗时代的金城。"),
(NULL,3,"img/destination/theme31.jpg","东京夜景","电影里的东京夜色令人无限向往，切身实地去感受东京的夜。"),
(NULL,3,"img/destination/theme32.jpg","光影米兰","光与影的曼妙结合，在米兰的夜晚上演。"),
(NULL,3,"img/destination/theme33.jpg","曼谷之夜","穿着人字拖，逛逛夜市，曼谷总是给人一舒服的感觉。"),
(NULL,3,"img/destination/theme34.jpg","夜行首尔","夜晚的明洞，繁忙又热闹，首尔的独特也在其中。"),
(NULL,3,"img/destination/theme35.jpg","不夜城香港","香港是个不夜城，夜宵美味，酣畅淋漓，夜不停息。"),
(NULL,3,"img/destination/theme36.jpg","俯瞰夜巴黎","凯旋门、卢浮宫、埃菲尔铁塔，俯瞰巴黎夜色。"),
(NULL,3,"img/destination/theme37.jpg","纽约酒吧","夜幕降临，你可以在酒吧中叫上三五好友一起嘬上一杯鸡尾酒或者啤酒，洗去上班或旅行的疲惫。"),
(NULL,4,"img/destination/theme41.jpg","纳斯卡线遗址","存在了2000年的谜局，这些被镶刻在大地之上的神秘线条，至今仍无人能破解——究竟是谁创造了纳斯卡线条、它们又是怎样创造出来的、神秘线条背后意味着什么？"),
(NULL,4,"img/destination/theme42.jpg","狮身人面像","狮身人面像简直就是三大金字塔的孪生兄弟，人们想起金字塔，紧接着就会想起狮身人面像。狮身人面像又叫斯芬克斯，传说中是巨人和蛇妖所生。"),
(NULL,4,"img/destination/theme43.jpg","图卢姆玛雅遗址","位于坎昆约130公里的加勒比海，是14世纪玛雅文化末期最繁荣的宗教都市遗迹。有高达3.3米高的石墙环绕。古城里的建筑都是用石头砌成的，雕刻着图案花纹。据说，这是迄今墨西哥保存最好的一座玛雅和托尔特克人的古城。"),
(NULL,4,"img/destination/theme44.jpg","马丘比丘","神秘的印加帝国遗迹。"),
(NULL,4,"img/destination/theme45.jpg","奇琴伊察","奇琴伊察古城遗址是最出名的、也是修复的最好的尤卡坦玛雅遗址，每个人都会伸长脖子看这个世界第七大奇观。"),
(NULL,4,"img/destination/theme46.jpg","巨石阵","在一大片草地中，这些横着竖着的大石头看似毫无规律的摆放，确是人类史的一大奇迹，考古学家认为其建于公元前3000年左右，这些距今已经有4300年的巨石是如何搬运和抬放依旧是迷。"),
(NULL,4,"img/destination/theme47.jpg","复活节岛","据人们推测，这些被称为摩艾的石雕像是岛上古老祭拜仪式的一部分，它们制成于公元1250年至1500年之间。"),
(NULL,5,"img/destination/theme51.jpg","比尔森","以啤酒出名的小镇，在这里可以品尝正宗的捷克啤酒。"),
(NULL,5,"img/destination/theme52.jpg","富士山","地方虽然不大，但却给人一种一尘不染的脱俗感。"),
(NULL,5,"img/destination/theme53.jpg","五渔村","依山而建的五颜六色的房子很美，海水很蓝很干净。"),
(NULL,5,"img/destination/theme54.png","洛迦诺","位于瑞士东南部提契诺州的马焦雷湖畔，宛如童话世界。"),
(NULL,5,"img/destination/theme55.jpg","高威","一个安静祥和，却不失活力元素，生活节奏慢的地方。"),
(NULL,5,"img/destination/theme56.jpg","布雷根茨","湖光山色，景色不错，紧挨瑞士德国，乃交通要塞。"),
(NULL,5,"img/destination/theme57.jpg","拉姆绍","非常漂亮的森林小镇，尤其是在阳光下，这里湖水的颜色是有层次的。");

/*月度推荐*/
CREATE TABLE traV_monthly_classify(
  mcl_id INT PRIMARY KEY AUTO_INCREMENT,
  mcl_name VARCHAR(32)
);
INSERT INTO traV_monthly_classify VALUES
(NULL,"1月"),
(NULL,"2月"),
(NULL,"3月"),
(NULL,"4月"),
(NULL,"5月"),
(NULL,"6月"),
(NULL,"7月"),
(NULL,"8月"),
(NULL,"9月"),
(NULL,"10月"),
(NULL,"11月"),
(NULL,"12月");
CREATE TABLE traV_monthly_info(
  mo_id INT PRIMARY KEY AUTO_INCREMENT,
  mcl_id INT,
  mo_lapic VARCHAR(256),
  mo_title VARCHAR(256),
  mo_info VARCHAR(256)
);
INSERT INTO traV_monthly_info VALUES
(NULL,1,"img/destination/month1_1.jpg","新西兰","在北半球处于寒冷的冬季的时候，南半球的新西兰正好春暖花开。世界上不太能再找出这么一个世外桃源，没有优胜劣汰的压力，没有变化极端的气候，只剩下一望无垠的美景，富饶多足的土地"),
(NULL,1,"img/destination/month1_2.jpg","韩国·江原道","你不用乘十几个小时飞机去地球的另外一边，韩国的这个地方就是为滑雪而生的。江原道的滑雪度假村有最天然的地理优势——60%以上都处于海拔700米。无论是菜鸟还是专业选手，无论是雪橇还是雪板，相信来过这里的人都会因征服雪山刺激感，而对这项运动感到“上瘾”。"),
(NULL,1,"img/destination/month1_3.jpg","美国·夏威夷","夏威夷是一个神奇的度假海岛，这里一年四季温暖如夏，不论你什么时候来，都能看到蓝天白云和椰林树影。威基基海滩大概是世界上最出名的海滩，也是多数游人心目中最典型的夏威夷海滩，这里有细致洁白的沙滩和众多摇曳多姿的椰子树。"),
(NULL,1,"img/destination/month1_4.jpg","泰国·苏梅岛","苏梅岛四面环海，大体上和泰国其他地方一样只有雨季和旱季，除了十到十二月之外，这里的气候都十分适合旅行。潜到海里看着海绵、珊瑚、海葵，上岸吃着这里的椰子和红毛丹，抑或去酒吧喝点啤酒释放激情。"),
(NULL,1,"img/destination/month1_5.jpg","俄罗斯·贝加尔湖","一年四季，每一个季节都是大自然给我们最好的时光。如果你能够欣赏冬季的美，那么去贝加尔湖一定没错。当你全身心的去感受冬季的美，那么其他的季节得模样就再也无法入了你的眼。"),
(NULL,2,"img/destination/month2_1.jpg","伊斯坦布尔","伊斯坦布尔古称君士坦丁堡，自古都是王者之地。曾作为奥斯曼帝国的首都，帝国极盛之时，势力波及欧亚非三大洲，君主苏丹更是将自己视为天下之主，然兵败于一战，帝国的大厦轰然倒塌。"),
(NULL,2,"img/destination/month2_2.jpg","乌兹别克斯坦·希瓦","希瓦是乌兹别克的一座古城，也曾是丝路重镇，王朝旧都。古为西域之地，其民风淳淳，如茗之烟。你大可以随意走进一家街边的餐馆，店主会轻巧一笑示意你落座，仿佛你不是他乡客，倒像是旧相识。"),
(NULL,2,"img/destination/month2_3.jpg","香港","这个季节的香港没有夏天的潮热，气温上更加舒适。三五天时间，飞去吃吃喝喝，顺便逛个小街，不能更舒服了。"),
(NULL,2,"img/destination/month2_4.jpg","摩洛哥","这个今年免签的彩色国度，每年11月至3月为旅行旺季。利用春节长假，骑骆驼深入撒哈拉，躺卧着看一亿颗星星；探索梅克内斯、菲斯和马拉喀什三大古城，以及瓦卢比利斯、阿伊特·本·哈杜村共5处世界文化遗产，穿越回《一千零一夜》的岁月。"),
(NULL,2,"img/destination/month2_5.jpg","瑞典","不管是不是最后一年的极光大爆发，每年的2月都是绝佳的看极光时机。瑞典具备观赏条件，而且性价比最高还”免签”，一起去做追光少年吧!"),
(NULL,3,"img/destination/month3_1.jpg","荷兰·丽兹","在荷兰，赏花地首推库肯霍夫公园。库肯霍夫号称世界上最美的春季公园，也是世界上最大的球茎花卉公园，园中各类花卉达600万株以上，是世界上被拍摄最多的地点，也是最受荷兰人钟爱的地方。"),
(NULL,3,"img/destination/month3_2.jpg","日本","每年3月15日至4月15日是日本的“樱花节”，正是樱花最盛放的时候。穿一袭和服，漫步在樱花雨下，会不会也和下雪天一样，一不小心就走到了白头。"),
(NULL,3,"img/destination/month3_3.jpg","韩国·济州岛","济州岛是韩国春天最早到来的地方，每到初春，油菜花便会率先开放。樱花的嫩粉和油菜花的艳黄，想象起来有些不搭调，不过在三月的济州岛，大自然给了我们一场精彩而又和谐的撞色T台秀。"),
(NULL,3,"img/destination/month3_4.jpg","印度","印度的色彩节就在三月。这是一个用色彩来迎接春天的节日，预示着灰暗的冬天的结束，五彩斑斓的春天即将到来。这一天，人们纷纷走上街头，跳舞狂欢，将彩色粉末涂满全身或是涂在他人额头表示祝福。"),
(NULL,3,"img/destination/month3_5.jpg","爱尔兰·都柏林","爱尔兰有个节日叫“绿帽子节”，人人都要带着绿帽子上街狂欢，它是为了纪念爱尔兰的守护神圣帕特里克，故又名圣帕特里克节。有些酒吧在节日期间还会出售特制的绿色啤酒，麦当劳也会出售绿色的奶昔。有机会一定要尝一尝。"),
(NULL,4,"img/destination/month4_1.jpg","美国·加利福尼亚","四月，春季，最适合来加州赏花。这个时候加州各个赏花胜地已经争奇斗艳起来了，风里都飘满着花香，空气里仿佛有糖一般，让身体和神经都在清新的空气里放松下来。"),
(NULL,4,"img/destination/month4_2.jpg","台湾·垦丁","第一次知道春天的呐喊垦丁音乐节是因为五月天的一首歌，歌词说“爽要呐喊，不爽更要喊，用力的呐喊，喊到流汗，喊到没遗憾，一生能有几次，跟世界宣战。”一生能有几次机会不顾一切地呐喊，不顾一切地狂欢，垦丁音乐节给你这个机会。"),
(NULL,4,"img/destination/month4_3.jpg","泰国","在曼谷、在芭提雅，到处都是蜂拥而至的人群，大家相互泼水、狂欢，享受清凉的“宋干节”。白天有灿烂的阳光、细腻的沙滩还有丰富的水上运动；夜晚则是另一种精彩：酒吧、音乐、表演，让整个城市充满激情，彻夜不眠。"),
(NULL,4,"img/destination/month4_4.jpg","希腊","复活节是西方国家的重要节日之一，但在希腊，复活节的庆祝活动却要比圣诞还丰富热闹。复活节期间，希腊的许多博物馆和景点都免费开放。趁着复活节，去希腊一探究竟，看看这个古老的国度真实的模样。"),
(NULL,4,"img/destination/month4_5.jpg","新加坡","4月是新加坡美食节，被称为“活的美食博物馆”。美食节期间，新加坡的到处是美食优惠信息，各个商家工厂也都在赶工，为了提供丰富的美食。一天五顿，顿顿都吃得爽快，把保持身材这种恼人的事尽情抛到脑后。"),
(NULL,5,"img/destination/month5_1.jpg","法国·巴黎","去巴黎，当然不能不去大大小小的博物馆，却不可避免地总是在大太阳底下排着长队。5月20日是巴黎的博物馆之夜。当晚，巴黎无数的博物馆将会免费开放。有一个免费在夜晚参观博物馆的机会当然不能错过，没准还会有像《博物馆奇妙夜》一样的奇遇呢。"),
(NULL,5,"img/destination/month5_2.jpg","伊朗·卡尚","玫瑰是卡尚旅游的一大主题。每年5月，全城充满了沁人心脾的玫瑰芬芳。在来自伊朗全国和世界各地的数万名游客注视下，当地人每天清晨摘下晶莹带露的“穆罕默迪”玫瑰花瓣，经过蒸馏等工艺，制成高品质玫瑰水。"),
(NULL,5,"img/destination/month5_3.jpg","捷克·布拉格","五月，是前往布拉格最好的时候。每年从5月12日起在捷克布拉格市内举行“布拉格之春国际音乐节”，开展为期三个礼拜的音乐活动。各种音乐流派在这里荟萃，它既是捷克最大型的音乐盛会，也是世界闻名的音乐节。"),
(NULL,5,"img/destination/month5_4.jpg","古巴·哈瓦那","穿梭在哈瓦那老城，迷宫般的大街小巷，路边一辆辆飞驰的复古车辆，仿佛穿越到了五十年代。古巴女郎、雪茄、朗姆酒、拉丁舞，一些属于古巴的名词让地方散发着迷人性感又神秘的气息。"),
(NULL,5,"img/destination/month5_5.jpg","美国·塞班","五月，塞班的凤凰花开的正旺盛。碧海蓝天，火红的凤凰花，红蓝的碰撞，给这个初夏一点不一样的色彩。背倚热带植被覆盖的山脉，穿过道路两旁郁郁葱葱的椰树展现在面前的是纯净透澈的蓝绿色菲律宾海，置身其中，仿佛身心都得到了净化。如果世上有天堂，大概就是这个模样。"),
(NULL,6,"img/destination/month6_1.jpg","俄罗斯·圣彼得堡","6月的俄罗斯清凉宜人，十分适合避暑度假。特别是圣彼得堡——这个世界上少数有“白夜”的城市，会在每年6月21日迎来盛大的节日——白昼节。"),
(NULL,6,"img/destination/month6_2.jpg","澳大利亚·塔斯马尼亚","正在发愁夏天看不到极光？不要怕，没有北极光，还可以有南极光。塔斯马尼亚岛，是澳洲最接近南极圈的地方，也是观赏南极光的最佳位置。现在出发，还能拥有极夜的独特体验。"),
(NULL,6,"img/destination/month6_3.jpg","坦桑尼亚","6月-9月的非洲，由于旱季的到来，数以百万计的野生动物将会上演地球上最壮观的大迁徙场面——从坦桑尼亚的塞伦盖蒂保护区前往肯尼亚的马赛马拉国家公园。"),
(NULL,6,"img/destination/month6_4.jpg","巴厘岛","6月的巴厘岛，迎来了一年当中最舒适的凉季——天气干爽，气候宜人。几乎不会下雨，夜晚清凉舒适。无论是阿勇河上的漂流、金巴兰海滩上完美的落日、还是圣泉寺里信徒虔诚的洗礼，都是一次最净化心灵的旅行。"),
(NULL,6,"img/destination/month6_5.jpg","阿根廷","每年六月阿根廷开始进入滑雪季，大部分滑雪胜地都全面开放，想要避暑滑雪，就不要错过六月的阿根廷啦。更何况，前些日子，阿根廷刚对中国开放了十年往返签证，是时候去世界的尽头看看了。"),
(NULL,7,"img/destination/month7_1.jpg","美国·华盛顿","每年的7月4号是美国的国庆日，又称独立日，为的是纪念1776年的这一天《独立宣言》的签署。而作为美利坚合众国的首都，华盛顿自然要举行一系列庆祝活动。"),
(NULL,7,"img/destination/month7_2.jpg","法国·巴黎","7月的巴黎，除了一年一度的夏季打折季和沙滩节之外，14日的法国国庆节也非常值得期待，法国国庆是为了纪念1789年的这一天巴黎人民攻占巴士底狱，那是个改变了法国乃至整个欧洲的日子。"),
(NULL,7,"img/destination/month7_3.jpg","蒙古·乌兰巴托","蒙古的国庆节在每年的7月11号，为了纪念1921年的这天蒙古人民革命党领导的人民革命取得胜利。而在国庆当天，也会举行盛大的那达慕大会开幕仪式。"),
(NULL,7,"img/destination/month7_4.jpg","意大利·翁布里亚","翁布里亚爵士音乐节也会在每年七月举行，这是世界上几大之知名的爵士音乐节之一，会持续一周左右的时间，每年这个时候，大区首府佩鲁贾都是游人云集，热闹非凡，爱好音乐的朋友一定不能错过。"),
(NULL,7,"img/destination/month7_5.jpg","挪威","7月的挪威非常凉爽，历史均温也不过十余度上下。挪威旅行最大的看点就是那刀凿斧琢般的海岸线上无数风景壮美的峡湾了，其间还散落着许多地质奇观。布道石，奇迹石，恶魔之舌……光听名字就令人神往。"),
(NULL,8,"img/destination/month8_1.jpg","非洲·马赛马拉","每年夏天，在东非广袤的大地上，为了追逐丰美的水草，上百万头食草动物都会长途跋涉3000多公里，上演这个星球上最壮观的迁徙。"),
(NULL,8,"img/destination/month8_2.jpg","俄罗斯·贝加尔湖","贝加尔湖古称北海，当年苏武便是于此牧羊。八月时节，原始森林葳蕤蓊郁，贝加尔湖瑰丽壮阔，气候宜人，生物成群。乘环湖火车赏景，湖边或可见一树一树的野花花开正盛，微风过处，落一地粉嫩鹅黄。"),
(NULL,8,"img/destination/month8_3.jpg","斐济","8月的斐济，天气较他时更为凉爽，且受热带风暴袭击的概率较低，适宜旅行。若能约上三两好友，在海岛上度过几天懒散闲适的生活，更复何求？"),
(NULL,8,"img/destination/month8_4.png","西班牙·布尼奥尔","每年8月的最后一个星期三，卡车都会在小镇上倾倒上百吨熟透的番茄，人们可以肆意地拿着番茄相互投掷，整个小镇都会成为红色的海洋。很少有这样的机会，可以将孩童的天性如此无拘无束地释放。"),
(NULL,8,"img/destination/month8_5.jpg","乌兹别克斯坦·撒马尔罕","撒马尔罕是乌兹别克斯坦的旧都，中亚大地最传奇的城市。这里是曾经的丝路重镇，八方通衢。世纪之初跻身世界文化遗产，被称为“文化交汇之地”。"),
(NULL,9,"img/destination/month9_1.jpg","新西兰·皇后镇","有人说，上帝先到了这里，然后才创造了天堂。9月的皇后镇开始进入春季，繁花似锦，是一年中最美的时候。除了绝美的自然风光之外，皇后镇还被誉为“冒险之都”，在这里可以体验许多世界顶级的户外活动。"),
(NULL,9,"img/destination/month9_2.jpg","意大利·米兰","9月的米兰天气日趋凉爽，除了宏伟的米兰大教堂和达芬奇的最后的晚餐真迹外，2017春夏米兰时装周也将于当地时间9月21日-9月26日举办。"),
(NULL,9,"img/destination/month9_3.jpg","德国·慕尼黑","九月下旬慕尼黑会举办举世闻名的啤酒节，人们用华丽的马车运送啤酒，身着传统巴伐利亚民族服饰盛装游行，在巨大的啤酒帐篷里开怀畅饮，欣赏巴伐利亚铜管乐队演奏的民歌乐曲。"),
(NULL,9,"img/destination/month9_4.jpg","加拿大","魁北克省和安大略省可以观赏加拿大的秋景，有万山红遍，层林尽染的美景。这里不仅有落基山空明澄澈的湖水、冰原大道千年不化的积雪、还有魁北克古城石板街的温婉浪漫、尼亚加拉大瀑布的恢宏壮阔和卡尔加里牛仔节魅力四射的激情……万千美景，集于一身。"),
(NULL,9,"img/destination/month9_5.jpg","突尼斯","9月下旬是突尼斯夏秋交替之季。此时地中海岸鲜花盛开，撒哈拉地区气温也开始转凉，是沙漠观景的好时节。这里也是欧洲人最喜爱的旅游胜地，一边是地中海的万顷碧波，一边是撒哈拉的无垠沙漠。在突尼斯感受三毛与荷西的撒哈拉平凡爱情也会是充满特殊浪漫的旅程。"),
(NULL,10,"img/destination/month10_1.jpg","俄罗斯·莫斯科","俄罗斯的十月入秋不久，气温稍凉，秋风飒爽。作为俄罗斯的首都，莫斯科是世界上绿化最好的城市之一，这时候来莫斯科，还可以看到最美的金秋。"),
(NULL,10,"img/destination/month10_2.jpg","瑞士","10月份是瑞士入秋的季节，这时候很适合徒步，并且游人较少。来这里，可以在国庆错峰出行，真正深入当地，体会民俗风情。"),
(NULL,10,"img/destination/month10_3.jpg","匈牙利·布达佩斯","布达佩斯一直享受着“多瑙河上的小明珠”之称号，美丽的多瑙河流经这座浪漫而又文艺的城市。走在秋季的布达佩斯，犹如进入了电影的世界。一年一度的秋季艺术节也在这个10月里举行。"),
(NULL,10,"img/destination/month10_4.jpg","南非","10月份南非刚刚开春，在开普敦等地区开满了鲜花，是旅行观光的最好时机。如果你不喜欢秋天，那么就去南非看花开吧"),
(NULL,10,"img/destination/month10_5.jpg","澳大利亚","每年的10月~次年2月是澳大利亚的夏季，也是澳大利亚最适合旅行的季节，阳光下的炫目海岸有无限诱惑力哦。澳洲是一个充满了生机的岛国，除了袋鼠和考拉，这里还有很多值得人们去体验的东西。比如花园城市墨尔本的有轨电车、大堡礁浮潜、黄金海岸的海鲜美味……"),
(NULL,11,"img/destination/month11_1.jpg","迪拜","11月至次年3月是迪拜的最佳旅行季节，这时的迪拜气候适宜、阳光和煦，在舒适的气候中更好的领略当地风情。作为目前世界上最高的建筑，高耸入云的迪拜塔已然成为迪拜的绝对地标。来迪拜游览这些独特的建筑，就能从中看到这几十年来穆斯林文化和西方文化碰撞的火花。"),
(NULL,11,"img/destination/month11_2.jpg","柬埔寨","如果你去过柬埔寨，你一定会被当地的古迹和历史气息震撼到，在吴哥窟林立的古迹中漫步，就好像看到了神秘的高棉历史。热带气候的柬埔寨，旱雨季交替明显。旱季（11月至4月）高温少雨，其中11月至1月属于凉季，气温在26摄氏度左右，非常宜人，很适合出游。"),
(NULL,11,"img/destination/month11_3.jpg","越南","越南沿着海岸线的狭长地带，河内与胡志明市这两座城市连起了顺化、岘港、会安、芽庄、美奈、大叻这一串美丽的小城。这就是越南，惊险之中却有别样风情的国家。刚刚结束暴雨季节的越南，进入凉季，也是越南最美的季节。"),
(NULL,11,"img/destination/month11_4.jpg","埃及","埃及冬季平均气温最高19. 9℃，最低9. 7℃，夏季温度最高可达三四十度。如果你想选择一个气温最舒适的时间去旅行，那么9至11月的埃及是最佳的选择。。金字塔，神庙，木乃伊，无一不是吸引着全世界各地的人们前往这里的理由。除此之外，埃及还有漂亮的红海，迷人的亚历山大港，淳朴热情的民众。"),
(NULL,11,"img/destination/month11_5.jpg","马尔代夫","十一月份可以避开圣诞的旅游高峰，也能享受到马尔代夫最舒适的少雨季节。 曾有人如此评价它：“如果你一生中有很多次出国旅游的机会，那你一定要来马尔代夫；如果你一生中只有一次出国旅游的机会，那你更要来马尔代夫”。"),
(NULL,12,"img/destination/month12_1.jpg","日本·白川乡","如果要去日本看雪，也许你第一个想到的是北海道。除了北海道之外，也许你可以尝试去一趟白川乡。白川乡是坐落于日本中部的岐阜县，是个四面环山、水田纵横、河川流经的安静村落。"),
(NULL,12,"img/destination/month12_2.jpg","芬兰·罗瓦涅米","大家都以为圣诞老人只是童话而已，但实际上芬兰就存在真正的圣诞老人。熟悉圣诞老人历史的人就会知道，他的家乡在拉普兰的罗瓦涅米。想去一睹圣诞老人的真容么？"),
(NULL,12,"img/destination/month12_3.jpg","美国","冬季的美国虽然没有夏季那么多有趣的玩乐项目，但你来这里却可以看到更加真实的它,遇到和美剧《老友记》中一样的普通人。圣诞节的时候，美国大街小巷上都会装饰起来，热闹的节日气氛感染着每一个人。"),
(NULL,12,"img/destination/month12_4.jpg","苏格兰·爱丁堡","如果你看过电影《一天》，那么你肯定记住了爱丁堡这座山城。整个城市浓郁而独特的文化气息，会让你置身于一个完全不同的世界中。当新年到来之时，你来到爱丁堡街头，绝对会被这新年的气氛所感染，和大家一起高呼、一起载歌载舞。"),
(NULL,12,"img/destination/month12_5.jpg","台北","台湾没有太多壮丽的山水，却有对景点细致的发掘。而跨年来这里，最不能错过的就是在台北101观景台体会「在烟火里看烟火」的奇妙经验。在迎接新年的时候，爬到台北101的89楼俯瞰整个城市，天空中绽放着整片整片的眼花。");

/*国家列表*/
CREATE TABLE traV_national_classify(
  nac_id INT PRIMARY KEY AUTO_INCREMENT,
  nac_name VARCHAR(32)
);
INSERT INTO traV_national_classify VALUES
(NULL,"亚洲"),
(NULL,"欧洲"),
(NULL,"非洲"),
(NULL,"北美"),
(NULL,"南美"),
(NULL,"大洋洲"),
(NULL,"南极洲");

CREATE TABLE traV_national_citys(
  naci_id INT PRIMARY KEY AUTO_INCREMENT,
  nac_id INT,
  nac_ChinName VARCHAR(128),
  nac_EgniName VARCHAR(256),
  nac_isHot VARCHAR(64)
);
INSERT INTO traV_national_citys VALUES
(NULL,1,"阿富汗","Afghanistan",""),
(NULL,1,"阿联酋","United Arab Emirates","热门"),
(NULL,1,"阿曼","Oman",""),
(NULL,1,"巴基斯坦","Pakistan",""),
(NULL,1,"巴勒斯坦","Palestine",""),
(NULL,1,"巴林","Bahrain",""),
(NULL,1,"不丹","Bhutan",""),
(NULL,1,"朝鲜","North Korea",""),
(NULL,1,"东帝汶","East Timor",""),
(NULL,1,"菲律宾 ","Philippines","热门"),
(NULL,1,"韩国","South Korea","热门"),
(NULL,1,"哈萨克斯坦","Kazakhstan",""),
(NULL,1,"柬埔寨","Cambodia","热门"),
(NULL,1,"吉尔吉斯斯坦","Kyrgyzstan",""),
(NULL,1,"卡塔尔","Qatar",""),
(NULL,1,"科威特","Kuwait",""),
(NULL,1,"老挝","Laos",""),
(NULL,1,"黎巴嫩","Lebanon",""),
(NULL,1,"马尔代夫","Maldives","热门"),
(NULL,1,"马来西亚","Malaysia","热门"),
(NULL,1,"蒙古","Mongolia",""),
(NULL,1,"孟加拉国","Bangladesh",""),
(NULL,1,"缅甸","Myanmar",""),
(NULL,1,"尼泊尔","Nepal","热门"),
(NULL,1,"日本","Japan","热门"),
(NULL,1,"沙特阿拉伯","Saudi Arabia",""),
(NULL,1,"斯里兰卡","Sri Lanka","热门"),
(NULL,1,"泰国","Thailand","热门"),
(NULL,1,"塔吉克斯坦","Tajikistan",""),
(NULL,1,"土库曼斯坦","Turkmenistan",""),
(NULL,1,"文莱","Brunei",""),
(NULL,1,"乌兹别克斯坦","Uzbekistan",""),
(NULL,1,"新加坡","Singapore","热门"),
(NULL,1,"叙利亚","Syria",""),
(NULL,1,"也门","Yemen",""),
(NULL,1,"伊拉克","Iraq",""),
(NULL,1,"伊朗","Iran",""),
(NULL,1,"印度","India","热门"),
(NULL,1,"印度尼西亚","Indonesia","热门"),
(NULL,1,"英属印度洋领地","British Indian Ocean Territory",""),
(NULL,1,"以色列","Israel",""),
(NULL,1,"约旦","Jordan",""),
(NULL,1,"越南","Vietnam","热门"),
(NULL,1,"中国","China","热门"),
(NULL,2,"阿尔巴尼亚","Albania",""),
(NULL,2,"爱尔兰","Ireland",""),
(NULL,2,"爱沙尼亚","Estonia",""),
(NULL,2,"安道尔","Andorra",""),
(NULL,2,"奥地利","Austria","热门"),
(NULL,2,"阿塞拜疆","Azerbaijan",""),
(NULL,2,"白俄罗斯","Belarus",""),
(NULL,2,"保加利亚","Bulgaria",""),
(NULL,2,"比利时"," Belgium","热门"),
(NULL,2,"冰岛","Iceland","热门"),
(NULL,2,"波黑","Bosnia & Herzegovina","热门"),
(NULL,2,"波兰","Poland","热门"),
(NULL,2,"丹麦","Denmark","热门"),
(NULL,2,"德国","Germany","热门"),
(NULL,2,"俄罗斯","Russia","热门"),
(NULL,2,"法国","France","热门"),
(NULL,2,"法罗群岛","Faroe Islands",""),
(NULL,2,"梵蒂冈","Vatican","热门"),
(NULL,2,"芬兰","Finland","热门"),
(NULL,2,"格陵兰","Greenland",""),
(NULL,2,"格鲁吉亚","Georgia","热门"),
(NULL,2,"黑山","Montenegro",""),
(NULL,2,"荷兰","Netherlands","热门"),
(NULL,2,"捷克","Czech Republic","热门"),
(NULL,2,"克罗地亚","Croatia","热门"),
(NULL,2,"科索沃","Kosovo",""),
(NULL,2,"拉脱维亚","Latvia",""),
(NULL,2,"列支敦士登","Liechtenstein",""),
(NULL,2,"立陶宛","Lithuania",""),
(NULL,2,"罗马尼亚","Romania",""),
(NULL,2,"卢森堡","Luxembourg","热门"),
(NULL,2,"马耳他","Malta",""),
(NULL,2,"马其顿","Macedonia",""),
(NULL,2,"摩尔多瓦","Moldova",""),
(NULL,2,"摩纳哥","Monaco","热门"),
(NULL,2,"挪威","Norway","热门"),
(NULL,2,"葡萄牙","Portugal","热门"),
(NULL,2,"瑞典","Sweden","热门"),
(NULL,2,"瑞士","Switzerland","热门"),
(NULL,2,"塞尔维亚 ","Serbia","热门"),
(NULL,2,"塞浦路斯","Cyprus",""),
(NULL,2,"圣马力诺","San Marino",""),
(NULL,2,"斯洛伐克","Slovakia",""),
(NULL,2,"斯洛文尼亚","Slovenia",""),
(NULL,2,"土耳其","Turkey","热门"),
(NULL,2,"乌克兰","Ukraine",""),
(NULL,2,"西班牙","Spain","热门"),
(NULL,2,"希腊","Greece","热门"),
(NULL,2,"西兰公国","Principality of Sealand",""),
(NULL,2,"匈牙利","Hungary","热门"),
(NULL,2,"亚美尼亚","Armenia",""),
(NULL,2,"意大利 ","Italy","热门"),
(NULL,2,"英国","UK","热门"),
(NULL,2,"直布罗陀","Gibraltar",""),
(NULL,3,"阿尔及利亚","Algeria",""),
(NULL,3,"埃及","Egypt","热门"),
(NULL,3,"埃塞俄比亚","Ethiopia",""),
(NULL,3,"安哥拉","Angola",""),
(NULL,3,"阿森松","Ascension",""),
(NULL,3,"贝宁","Benin",""),
(NULL,3,"北苏丹王国","Kingdom of North Sudan",""),
(NULL,3,"博茨瓦纳","Botswana",""),
(NULL,3,"布基纳法索","Burkina Faso",""),
(NULL,3,"布隆迪","Burundi",""),
(NULL,3,"赤道几内亚","Equatorial Guinea",""),
(NULL,3,"佛得角","Cape Verde",""),
(NULL,3,"多哥","Togo",""),
(NULL,3,"厄立特里亚","Eritrea",""),
(NULL,3,"冈比亚","Gambia",""),
(NULL,3,"刚果","Congo-Brazzaville",""),
(NULL,3,"刚果民主共和国 ","Congo-Kinshasa",""),
(NULL,3,"加纳","Ghana",""),
(NULL,3,"加蓬","Gabon",""),
(NULL,3,"吉布提","Djibouti",""),
(NULL,3,"津巴布韦","Zimbabwe",""),
(NULL,3,"几内亚 ","Guinea",""),
(NULL,3,"几内亚比绍 ","Guinea Bissau",""),
(NULL,3,"喀麦隆","Cameroon",""),
(NULL,3,"科摩罗","Comoros",""),
(NULL,3,"肯尼亚","Kenya",""),
(NULL,3,"科特迪瓦","Cote Divoire",""),
(NULL,3,"莱索托","Lesotho",""),
(NULL,3,"利比里亚","Liberia",""),
(NULL,3,"利比亚","Libya",""),
(NULL,3,"留尼汪 ","Reunion",""),
(NULL,3,"卢旺达","Rwanda",""),
(NULL,3,"马达加斯加","Madagascar",""),
(NULL,3,"马拉维","Malawi",""),
(NULL,3,"马里","Mali",""),
(NULL,3,"毛里求斯","Mauritius",""),
(NULL,3,"毛里塔尼亚","Mauritania",""),
(NULL,3,"马约特","Mayotte",""),
(NULL,3,"摩洛哥","Morocco","热门"),
(NULL,3,"莫桑比克","Mozambique",""),
(NULL,3,"纳米比亚","Namibia",""),
(NULL,3,"南非","South Africa",""),
(NULL,3,"南苏丹","South Sudan",""),
(NULL,3,"尼日尔","Niger",""),
(NULL,3,"尼日利亚","Nigeria",""),
(NULL,3,"塞拉利昂","Sierra Leone",""),
(NULL,3,"塞内加尔","Senegal",""),
(NULL,3,"塞舌尔","Seychelles",""),
(NULL,3,"圣多美和普林西比","Sao Tome & Principe",""),
(NULL,3,"圣赫勒拿","Saint Helena",""),
(NULL,3,"艾史瓦帝尼王国（斯威士兰）","Kingdom of eSwatini(Swaziland)",""),
(NULL,3,"苏丹","Sudan",""),
(NULL,3,"索马里","Somalia",""),
(NULL,3,"坦桑尼亚","Tanzania",""),
(NULL,3,"特里斯坦-达库尼亚群岛","Tristan da Cunha",""),
(NULL,3,"突尼斯","Tunisia",""),
(NULL,3,"乌干达","Uganda",""),
(NULL,3,"西撒哈拉","Western Sahara",""),
(NULL,3,"赞比亚","Zambia",""),
(NULL,3,"乍得","Chad",""),
(NULL,3,"中非共和国","Central African Republic",""),
(NULL,4,"安圭拉","Anguilla",""),
(NULL,4,"安提瓜和巴布达","Antigua & Barbuda",""),
(NULL,4,"巴巴多斯","Barbados",""),
(NULL,4,"巴哈马","The Bahamas",""),
(NULL,4,"百慕大","Bermuda",""),
(NULL,4,"巴拿马","Panama",""),
(NULL,4,"波多黎各","Puerto Rico",""),
(NULL,4,"伯利兹","Belize",""),
(NULL,4,"阿鲁巴","Aruba",""),
(NULL,4,"波内赫 ","Bonaire",""),
(NULL,4,"多米尼加共和国","Dominican Republic",""),
(NULL,4,"多米尼克","Dominica",""),
(NULL,4,"法属圣马丁","Saint Martin",""),
(NULL,4,"格林纳达","Grenada",""),
(NULL,4,"哥斯达黎加","Costa Rica",""),
(NULL,4,"瓜德罗普","Guadeloupe",""),
(NULL,4,"古巴","Cuba",""),
(NULL,4,"海地","Haiti",""),
(NULL,4,"荷属圣马丁","Sint Maarten",""),
(NULL,4,"洪都拉斯","Honduras",""),
(NULL,4,"加拿大","Canada","热门"),
(NULL,4,"开曼群岛","Cayman Islands",""),
(NULL,4,"库拉索","Curacao",""),
(NULL,4,"马提尼克","Martinique",""),
(NULL,4,"美国 USA","","热门"),
(NULL,4,"美属维尔京群岛","US Virgin Islands",""),
(NULL,4,"蒙塞拉特岛","Montserrat",""),
(NULL,4,"墨西哥","Mexico","热门"),
(NULL,4,"尼加拉瓜","Nicaragua",""),
(NULL,4,"萨巴岛","Saba",""),
(NULL,4,"萨尔瓦多","El Salvador",""),
(NULL,4,"圣巴泰勒米岛","Saint-Barthelemy",""),
(NULL,4,"圣基茨和尼维斯","Saint Kitts and Nevis",""),
(NULL,4,"圣卢西亚"," St Lucia",""),
(NULL,4,"圣皮埃尔和密克隆群岛","Saint Pierre et Miquelon",""),
(NULL,4,"圣文森特和格林纳丁斯","St Vincent & The Grenadines",""),
(NULL,4,"圣尤斯特歇斯","Sint Eustatius",""),
(NULL,4,"特克斯和凯科斯群岛","Turks & Caicos Islands",""),
(NULL,4,"特立尼达和多巴哥","Trinidad & Tobago",""),
(NULL,4,"危地马拉","Guatemala",""),
(NULL,4,"牙买加","Jamaica",""),
(NULL,4,"英属维尔京群岛","British Virgin Islands",""),
(NULL,5,"阿根廷","Argentina",""),
(NULL,5,"巴拉圭","Paraguay",""),
(NULL,5,"巴西","Brazil",""),
(NULL,5,"秘鲁","Peru",""),
(NULL,5,"玻利维亚","Bolivia",""),
(NULL,5,"厄瓜多尔","Ecuador",""),
(NULL,5,"法属圭亚那","French Guiana",""),
(NULL,5,"福克兰群岛（马尔维纳斯群岛）","Falkland Islands",""),
(NULL,5,"哥伦比亚","Colombia",""),
(NULL,5,"圭亚那","Guyana",""),
(NULL,5,"苏里南","Suriname",""),
(NULL,5,"委内瑞拉","Venezuela",""),
(NULL,5,"乌拉圭 ","Uruguay",""),
(NULL,5,"智利","Chile",""),
(NULL,6,"艾普罗菲尔","Apolofirl",""),
(NULL,6,"澳大利亚","Australia","热门"),
(NULL,6,"巴布亚新几内亚","Papua New Guinea",""),
(NULL,6,"北马里亚纳群岛","Northern Mariana Islands",""),
(NULL,6,"法属波利尼西亚","French Polynesia",""),
(NULL,6,"斐济","Fiji",""),
(NULL,6,"关岛","Guam",""),
(NULL,6,"基里巴斯","Kiribati",""),
(NULL,6,"库克群岛","The Cook Islands",""),
(NULL,6,"马绍尔群岛","Marshall Islands",""),
(NULL,6,"美属萨摩亚","American Samoa",""),
(NULL,6,"密克罗尼西亚联邦","Federated States Of Micronesia",""),
(NULL,6,"瑙鲁","Nauru",""),
(NULL,6,"纽埃","Niue",""),
(NULL,6,"帕劳","Palau",""),
(NULL,6,"皮特凯恩群岛 ","Pitcairn Islands",""),
(NULL,6,"萨摩亚","Samoa",""),
(NULL,6,"所罗门群岛","Solomon Islands",""),
(NULL,6,"汤加","Tonga",""),
(NULL,6,"托克劳","Tokelau",""),
(NULL,6,"图瓦卢","Tuvalu",""),
(NULL,6,"瓦利斯群岛和富图纳群岛","Wallis & Futuna",""),
(NULL,6,"瓦努阿图","Vanuatu",""),
(NULL,6,"新喀里多尼亚","New Caledonia",""),
(NULL,6,"新西兰","New Zealand","热门"),
(NULL,7,"布韦岛","Bouvet Island",""),
(NULL,7,"法属南部领土","French Southern Territories",""),
(NULL,7,"南极","Antarctica",""),
(NULL,7,"南乔治亚岛和南桑威奇群岛","SGSSI",""),
(NULL,7,"太空","Outer Space","");

/*穷游论坛中轮播图中的数据*/
CREATE TABLE traV_forum_banner(
  fb_id INT PRIMARY KEY AUTO_INCREMENT,
  fd_bpic VARCHAR(256),
  fd_hpic VARCHAR(256),
  fd_hiconpic VARCHAR(256),
  fd_hname VARCHAR(128),
  fd_htitle VARCHAR(128),
  fd_bdeatail VARCHAR(256)
);
INSERT INTO traV_forum_banner VALUES
(NULL,"img/forum/banner1.jpg","img/forum/bhead1.jpg","img/forum/headicon.png","爱溜达的猫","穷游资深精华作者，问答探路者","南纬18度的避世秘境--瓦努阿图"),
(NULL,"img/forum/banner2.jpg","img/forum/bhead2.jpg","img/forum/headicon.png","多多熊","穷游资深精华作者","【你的世界地图长什么样】之【挪威，你那么美，你那么媚】（北欧游记挪威篇，附挪威详细自由行..."),
(NULL,"img/forum/banner3.jpg","img/forum/bhead3.jpg","img/forum/headicon.png","念小遗","穷游资深精华作者","「流奶与蜜」的应许:耶路撒冷 Promised Land：Jerusalem（耶路撒冷6日深度游）"),
(NULL,"img/forum/banner4.jpg","img/forum/bhead4.jpg","img/forum/headicon.png","阿呀阿拉蕾","穷游资深精华作者","打开南美，【阿拉蕾】带你发现足球王国巴西的故事"),
(NULL,"img/forum/banner5.jpg","img/forum/bhead5.jpg","img/forum/headicon.png","晨曦寒萧","穷游精华作者","穷奢极意 • 七宗最");

/*游记攻略数据*/
CREATE TABLE traV_forum_method(
  fm_id INT PRIMARY KEY AUTO_INCREMENT,
  fm_headPic VARCHAR(256),
  fm_headName VARCHAR(128),
  fm_place VARCHAR(128),
  fm_likes INT,
  fm_title VARCHAR(256),
  fm_datial VARCHAR(256),
  fm_howgood INT,
  fm_pic VARCHAR(256),
  fm_releaseTime VARCHAR(64),
  fm_isgoodauthor VARCHAR(128)
);
INSERT INTO traV_forum_method VALUES
(NULL,"img/forum/mdh1.jpg","爱画画的单眼皮","阿联酋/卡塔尔",159,"【对世界上瘾——迪拜篇】用平价的交通工具解锁土豪的国度（完结）","【前  言】从2016年第一次自由行开始，坚持每年都出去一次，每年回来都写游记，虽然不完美，但是，我真的想有一篇能评上精华。这次迪拜之行...",1,"img/forum/md1.jpg","最后回复于9小时前",""),
(NULL,"img/forum/mdh2.jpg","念小遗","西班牙/葡萄牙/安道尔",903,"【我在欧洲天旋地转Spinning Around】如沐暖阳.醉梦伊比利亚（西班牙全攻略.手把手票务.交通.购物.米其林）","序.如沐暖阳每年的春节，总想逃离北京的寒冬，去一个明媚的地方享受阳光屏蔽海岛的烈日炎炎，追逐那份冬日暖阳，才是我的心头爱2019年的春节...",3,"img/forum/md2.jpg","最后回复于56分钟前","穷游资深精华作者"),
(NULL,"img/forum/mdh3.jpg","海清石","自驾",31,"德国巴伐利亚州慕尼黑、新天鹅堡、菲森三日行记"," 行前准备    结束了与朋友在克罗地亚的自驾行程后，我们暂时与朋友分道，她们继续自驾前往捷克和匈牙利旅行，我们则北上德国慕尼黑，弥补一下之...",0,"img/forum/md3.jpg","最后回复于11小时前",""),
(NULL,"img/forum/mdh4.jpg","谢旭","非洲其他国家",306,"探险马达加斯加：从原始到文明的蜕变（山人游记26）","前言马达加斯加算是世界上最奇特的国家了：地处非洲却鲜有非洲文化；身为世界第四大岛，国土面积是新西兰的两倍多却是世界战略地位最低的国...",1,"img/forum/md4.jpg","最后回复于14小时前",""),
(NULL,"img/forum/mdh5.jpg","年华橙橙","缅甸",376,"首页纪念 从丹老秘境到千塔佛国——缅甸2019新春扶老携幼的14个日与夜（760图含游览线、主景点地图、蒲甘可爬塔坐标）","哇哦，撒花纪念上穷游首页纪念一下上缅甸板块首页开篇   由于2018年暑假27天美西游回来耗能较大，在选择2019年家庭跨年游目的地的时候，本着...",2,"img/forum/md5.jpg","最后回复于1小时前","穷游精华作者"),
(NULL,"img/forum/mdh6.jpg","AuroraYu24","带孩子旅行",201,"2019男孩节带娃看世界第一站—关西，附京都奈良大阪全方位亲子游攻略及网红餐厅一手预约经验（已完结）","题记：楼主前一篇帖子预告过，5月初要带娃（马上2岁，薅航空公司羊毛）去日本过男孩节，还在今年春节的时候去关西踩了一次点，所以本帖主要...",1,"img/forum/md6.jpg","最后回复于1小时前",""),
(NULL,"img/forum/mdh7.jpg","xiaoputao0501","日本",1244,"【首页纪念】葡萄夫妇枫叶季游日本九州，福冈|佐贺|鹿儿岛|指宿|熊本|由布院|别府|广岛|大久野岛超强实用攻略，客路体验","容登首页4.12喜提穷游首页~~~撒花预告片欣赏【鹿儿岛】喷发的樱岛火山【鹿儿岛】天文馆站前【鹿儿岛】城山酒店展望台【樱岛】赤水展望广场...",3,"img/forum/md7.jpg","最后回复于2小时前","穷游资深精华作者"),
(NULL,"img/forum/mdh8.jpg","Sunny酱闯天下","台湾",149,"【左手大海，右手美食】台湾十日半岛漫游记（保姆级攻略：台北/花莲/垦丁/台南/美食/赏萤等/附海量美图/已完结）","去年冬天，好久不见的大学室友约着吃饭，给我带了一盒台湾的微热山丘凤梨酥。之前就知道台湾好吃的很多，但是知识范围只限于夜市。当朋友给...",2,"img/forum/md8.jpg","最后回复于5小时前",""),
(NULL,"img/forum/mdh9.jpg","big_michael","荷兰/比利时/卢森堡",134,"低地三国环游记——一村一景致、一城一大师，荷比卢5村10城21天","写在前面——尼德兰是哪？为什么要去那？每次跟朋友聊旅游，几乎都会被问到同一个问题：下次去哪？几个月前当我被问到这个问题时脱口而出：...",0,"img/forum/md9.jpg","最后回复于9小时前",""),
(NULL,"img/forum/mdh10.jpg","旅行梦享家","中国内地",261,"正确的打开方式，像个土著一样玩舟山——舟山私房景点、美食攻略大放送","前言提到舟山，很多人想到的，无非是海天佛国普陀山，碧海金沙桃花岛，金庸笔下桃花岛，还有最近大热的东极岛、嵊泗列岛。很多人来舟山，是...",1,"img/forum/md10.jpg","最后回复于18小时前","问答探路者，穷游资深精华作者"),
(NULL,"img/forum/mdh11.jpg","马帮猪猪","英国/爱尔兰",64,"【猪猪原创】英国南部海岸自驾流浪- 英格兰威尔士National trust非著名美景一网打尽","本贴是我写的UK三部曲的最后一篇，之前发布过第一篇【猪猪原创】三周自驾走遍英伦三岛- 英格兰及苏格兰篇（三星精华贴）以及第二篇【猪猪...",0,"img/forum/md11.jpg","最后回复于8小时前",""),
(NULL,"img/forum/mdh12.jpg","lsm971229","澳大利亚",272,"回望袋鼠国行摄匆匆之南大洋自驾游(墨尔本-大洋路-石灰岩海岸-袋鼠岛-阿德莱德)","2019年的春节，我和家人再次从寒冷的北方跑到了南半球度过了一个温暖的假期，只不过这次不是新西兰，而是让人向往又让人略有些惆怅的澳大...",1,"img/forum/md12.jpg","最后回复于11小时前",""),
(NULL,"img/forum/mdh13.jpg","贩暖","尼泊尔",251,"尘埃与菩提，尼泊尔的幻境（附中尼、尼印边境陆路过境攻略）","跟尼泊尔的缘分大概要追溯到7年前了，那是2012年离开职场开始独自背包旅行，计划之外的决定去了珠峰，却错过了从 樟木 口岸前往 尼泊尔 。后...",1,"img/forum/md13.jpg","最后回复于14小时前","穷游资深精华作者"),
(NULL,"img/forum/mdh14.jpg","楠晓黄","菲律宾",196,"菲律宾记（科隆岛深度游、补订航空行李攻略、大量美图）","前言：菲律宾在我看来，这是一个一半天堂，一半地狱的国度。虽然天蓝水清，繁花似锦，风光无限，但在美丽的外表下但掩盖着那么多极度贫穷的...",1,"img/forum/md14.jpg","最后回复于12分钟前","穷游精华作者"),
(NULL,"img/forum/mdh15.jpg","爱画画的单眼皮","阿联酋/卡塔尔",159,"【对世界上瘾——迪拜篇】用平价的交通工具解锁土豪的国度（完结）","【前  言】从2016年第一次自由行开始，坚持每年都出去一次，每年回来都写游记，虽然不完美，但是，我真的想有一篇能评上精华。这次迪拜之行...",1,"img/forum/md15.jpg","最后回复于18小时前",""),
(NULL,"img/forum/mdh16.jpg","AllenL艾伦伦","台湾",655,"【春节环台】十日温存间，用思恋补完最后的诗篇（桃园-高雄-垦丁-花莲-九份-台北自由行全攻略）—KLOOK客路","前言 | 且行且憶终于，我来了曾经多少次幻想过自己抵达台湾时的模样或张扬，或惆怅却未尝意料到如今一切会来得这么平静静到当我站在桃园机场...",3,"img/forum/md16.jpg","最后回复于13小时前","穷游资深精华作者"),
(NULL,"img/forum/mdh17.jpg","旅行梦享家","越南",650,"万种风情如是你,八天玩转越南北（河内、岘港、巴拿山、会安、顺化、迦南岛、芽庄、大叻、珍珠岛，客路体验，详尽攻略应有尽有）","前言关于越南，出行前，充满了期待和不安。期待万盏灯火的迷人会安，期待如童话世界般的大叻、巴拿山，期待美味的越南美食，还有那些关于越...",2,"img/forum/md17.jpg","最后回复于14小时前","问答探路者，穷游资深精华作者"),
(NULL,"img/forum/mdh18.jpg","硕饱儿","伊朗",1045,"归来不看清真寺：伊朗——江山无数，一眼千年 | 结伴8日 | 卡尚、伊斯法罕、亚兹德、波斯波利斯、设拉子、德黑兰","前言从伊朗回来的那几天，我一直不能抑制自己兴奋的心情。每天看书复习觉得倦怠的时候，就去摩挲一下我从伊朗带回来的毯子——富有故事性的...",3,"img/forum/md18.jpg","最后回复于8小时前","穷游资深精华作者"),
(NULL,"img/forum/mdh19.jpg","年华橙橙","美国",101,"（全文完）苍茫美西 —— 一家三口的26天暑期亲子7500公里大环线  2000多精美照片，超详细干货","往期游记缅甸14天游记：首页纪念 从丹老秘境到千塔佛国——缅甸2019新春扶老携幼的14个日与夜（760图含游览线、主景点地图、蒲甘可爬塔坐...",2,"img/forum/md19.jpg","最后回复于14小时前","穷游精华作者"),
(NULL,"img/forum/mdh20.jpg","KrisYu小姐","潜水俱乐部",176,"菲律宾 | 炎炎夏日 来一罐沙丁鱼罐头吧 (杜马盖地，墨宝，OSLOB交通潜水攻略）","题记：Open a Sadine Can in the crystal blue!去年一年都没有机会潜水，所以趁着宿务航空机票大促，买了上海往返杜马盖地的机票，打算来刷一...",1,"img/forum/md20.jpg","最后回复于16小时前","穷游资深精华作者"),
(NULL,"img/forum/mdh21.jpg","沐峭","南美/南极",253,"菲律宾 | 炎炎夏日 来一罐沙丁鱼罐头吧 (杜马盖地，墨宝，OSLOB交通潜水攻略）","题记：Open a Sadine Can in the crystal blue!去年一年都没有机会潜水，所以趁着宿务航空机票大促，买了上海往返杜马盖地的机票，打算来刷一...",2,"img/forum/md21.jpg","最后回复于11小时前","问答探路者，穷游资深精华作者"),
(NULL,"img/forum/mdh22.jpg","菲利斯斯斯密达","日本",226,"【从平成走向令和】——2019五一7日6晚东京游（东京/箱根/镰仓/日光/吉祥寺）——带着妈妈外婆去日本","【行程缩影】2019年的四月底五一初，对于日本人来说，并不平凡告别平成，迎接令和当地人10天长假，让我也感受了一把日本的人人人人~这一...",1,"img/forum/md22.jpg","最后回复于21小时前",""),
(NULL,"img/forum/mdh23.jpg","HelloEleven","环游欧洲",447,"跟随画笔，连线浪漫葡西法（葡萄牙-西班牙-南法10日自由行）","（这次又有很多旅行插画哦，你能找到它们吗？）前言“接下来怎么办？”我们的车开在南法普罗旺斯的乡间小道上，一路畅通，但是我们俩...",2,"img/forum/md23.jpg","最后回复于1天前","穷游精华作者"),
(NULL,"img/forum/mdh24.jpg","秣秣","中国内地",166,"微微一笑，晋尚晋美（山西古建之旅）","微微一笑，晋尚晋美晋北之旅，类似于临时起意，约上同好者，不是节假日，不是暑期，机票合适就买了，国内旅行感觉可以随时拎包出发。距离...",2,"img/forum/md24.jpg","最后回复于17小时前","穷游精华作者"),
(NULL,"img/forum/mdh25.jpg","in老板","香港/澳门",72,"香港迪士尼乐园，用48小时Get全世界的快乐（2019新玩法登陆）","一场《复联4》的真实大冒险从2008的《钢铁侠1》到2019年的《复仇者联盟4》，漫威11年一路追随。从年少青葱到即将与青春告别，11年的光阴...",1,"img/forum/md25.jpg","最后回复于14小时前","穷游资深精华作者"),
(NULL,"img/forum/mdh26.jpg","KyleShi","东非地区",417,"果小姐的慢生活之回到世界最初的模样（坦桑尼亚、津巴布韦）","是的，我又来非洲了。——题记",3,"img/forum/md26.jpg","最后回复于22小时前","穷游资深精华作者"),
(NULL,"img/forum/mdh27.jpg","饭团karenchow","波兰/立陶宛/拉脱维亚/爱沙尼亚",267,"波罗的海|立陶宛与拉脱维亚的阴与晴（含地道美食餐厅推荐）","一场突如其来的出差，让我闯入 波罗的海 ，遇见了这样两个有点与世无争的小国—— 立陶宛 与 拉脱维亚 （ 波罗的海 指三个国家： 立陶宛 、 拉...",1,"img/forum/md27.jpg","最后回复于18小时前","穷游资深精华作者"),
(NULL,"img/forum/mdh28.jpg","萝卜哒哒","邮轮",483,"旅行趁早——维京游轮莱茵河11天极致踏春体验（已完结）","春天是我最喜欢的季节，也因此每年春天都会是我最忙的时候，要么每个周末都会自驾到北京周边的山林里踏春，要么就会策划一次长途旅行，去寻...",1,"img/forum/md28.jpg","最后回复于2天前","穷游精华作者"),
(NULL,"img/forum/mdh29.jpg","AngelEmme","荷兰/比利时/卢森堡",263,"遇见 • 独行荷兰十日记 - 国宝地图, 花田骑行, 美食寻踪, 邂逅大师展, 狂欢国王节, 不负最美春天!","Section-1  续 ：何谓我的“遇见”?这是我“遇见”系列的第四篇游记。（容我再叙述一遍）何谓我的“遇见”？旅行对不同的人有不同的意义，...",1,"img/forum/md29.jpg","最后回复于2天前",""),
(NULL,"img/forum/mdh30.jpg","为食猫在路上","俄罗斯/乌克兰/白俄罗斯",94,"俄国行 -- 记2019年5.1莫斯科、圣彼得堡9天之旅","前言：去俄罗斯看一看的想法似乎已存在已久，说不上为什么，或者根本不需要理由，从心出发才是旅游最好的初衷，基于这个想法，暴走二人组再...",1,"img/forum/md30.jpg","最后回复于1天前","穷游精华作者"),
(NULL,"img/forum/mdh31.jpg","janice_wj","希腊/塞浦路斯",21,"2019年春天，遇见希腊那片蓝（雅典、迈泰奥拉 、圣托里尼、凯法利尼亚、扎金索斯）13天境内飞机+火车+渡轮+自驾","一、前言这次旅行，可以说是临时决定的，也可以说是早就计划好的。说早就计划好，是因为攻略在3月初就做好了，计划5月出行，后来由于同行的...",0,"img/forum/md31.jpg","最后回复于2天前",""),
(NULL,"img/forum/mdh32.jpg","Li_Yanan","西亚其他国家",767,"中东腹地（在大马士革跨年，在叙利亚前线亲历伊斯兰国覆灭，详尽的政府军叙利亚+罗贾瓦叙利亚+阿拉伯伊拉克+库尔德伊拉克）","开端这可能是一篇很长的帖子，详尽展示中东腹地的伊拉克和叙利亚的各种内容。自2017至2019年之间，我三次进入叙利亚的不同区域，两次进入...",1,"img/forum/md32.jpg","","穷游资深精华作者"),
(NULL,"img/forum/mdh33.jpg","天天的世界地图","尼泊尔",600,"【走进喜马拉雅】尼泊尔安娜普尔纳大环线徒步（ACT+Tilicho Lake）含详细攻略（已完结） ","【前言】2018年，我辞掉了世界五百强企业稳定的工作，来到尼泊尔一侧的喜马拉雅山麓。穿上沾满尘土的徒步鞋，背起二十多斤重的行囊，把登...",3,"img/forum/md33.jpg","最后回复于2天前","穷游资深精华作者"),
(NULL,"img/forum/mdh34.jpg","邹雯艾","新加坡",288,"来~!让我跟你聊聊新加坡的秘境小众美景","一、前言：新加坡，一个再也不能熟悉的国家，当年读书在新加坡生活了很多年，现在也每隔2、3年就会回去逛一逛，但从来没认真的拍过新加坡。...",1,"img/forum/md34.jpg","最后回复于2天前","穷游资深精华作者"),
(NULL,"img/forum/mdh35.jpg","红狐在天","美国",254,"海洋与沙漠，繁华与孤独，即便结束，也难忘于回忆！美西12日谈（短期探寻经典美西城市和国家公园的必备行程）","序言对于远在太平洋彼岸的美国，谈不上特别的热爱，也说不上来讨厌。对于他的情怀，既没有香港那种从小对于港片的不断灌输与回忆，也没有曾...",1,"img/forum/md35.jpg","最后回复于2天前","穷游精华作者"),
(NULL,"img/forum/mdh36.jpg","姗姗来迟310","德国",323,"落叶有声——记录行走在德国和捷克（柏林、德累斯顿、布拉格）的八天，含德铁DB购票、国会大厦预订、柏林爱乐预订等。","一、从何说起？*柏林柏林，一座经过两次世界大战的城市，很多攻略或是游记都说这是个活生生的历史，是个离我们最近的历史。对于历史，柏林...",1,"img/forum/md36.jpg","最后回复于12分钟前","");

/*结伴同游的数据库表*/
CREATE TABLE traV_forum_friends(
  ff_id INT PRIMARY KEY AUTO_INCREMENT,
  ff_headpic VARCHAR(256),
  ff_headName VARCHAR(128),
  ff_lookcun INT,
  ff_responsecun INT,
  ff_releasetime VARCHAR(128),
  ff_detail VARCHAR(256),
  ff_gotime VARCHAR(32),
  ff_backtime VARCHAR(32),
  ff_places VARCHAR(64)
);
INSERT INTO traV_forum_friends VALUES
(NULL,"img/forum/fh1.jpg","yeqiangweishen",2,0,"最后回复于15分钟前","计划7.8到7.15到banff，jasper，yoho自驾游，需要再找个会开车","2019-07-08","2019-07-16","加拿大、温哥华、加拿大、维多利亚市"),
(NULL,"img/forum/fh2.jpg","user_D6yD0NlS7r",3,0,"最后回复于16分钟前","英语超溜人超级Nice的85后小姐姐（老阿姨）求伊斯坦布尔同游","2019-07-04","2019-07-08","土耳其、伊斯坦布尔"),
(NULL,"img/forum/fh3.jpg","我们应该有梦",4,0,"最后回复于18分钟前","一起去西藏吗？想约个伴","2019-07-08","2019-07-31","中国、西藏"),
(NULL,"img/forum/fh4.jpg","user_hERG0NlRZ1",3,0,"最后回复于18分钟前","好想找个女生一起东南亚旅游，随时可以走的。最近心情郁闷。费用可以一个人全出","2019-07-10","2019-07-18","印度尼西亚、巴厘岛"),
(NULL,"img/forum/fh5.jpg","箫帅",1,0,"最后回复于19分钟前","火热的七月，上有天堂，下有苏州，去看苏州小桥流水人家，去聆听夜半钟声到客船！","2019-07-08","2019-07-20","	中国、苏州"),
(NULL,"img/forum/fh6.jpg","骑耗子追猫",0,0,"最后回复于19分钟前","北京人在成都，想交点朋友一起走走转转吃吃喝喝玩玩乐乐","2019-07-08","2019-07-20","	中国、成都"),
(NULL,"img/forum/fh7.jpg","淇耕",2,0,"最后回复于19分钟前","七月末有一起去张家界3天短游的小伙伴吗？如有意向可加我商量516408038。广","2019-07-27","2019-07-29","中国、湖南"),
(NULL,"img/forum/fh8.jpg","袁先森-",3,0,"最后回复于21分钟前","7月22号到天津，有一起游玩的小姐姐吗，旅宿费用我来！","2019-07-22","2019-07-23","中国、天津"),
(NULL,"img/forum/fh9.jpg","小蓓爱旅行耶耶耶",3,0,"最后回复于21分钟前","夫妻二人，来自上海，7.15-7.17计划三天自驾一号公路，从旧金山到洛杉矶。两","2019-07-15","2019-07-17","	美国、大瑟尔、加州一号公路"),
(NULL,"img/forum/fh10.jpg","西行途行",1,0,"最后回复于5分钟前","7月5号7月8号7月16号7月25号8月等等成都集合出发西藏，稻城亚丁，色达，全","2019-07-04","2019-07-07","西藏，稻城亚丁"),
(NULL,"img/forum/fh11.jpg","无人像你l",1,0,"最后回复于11分钟前","有一起的小姐姐吗","2019-07-17","2019-07-25","中国、青岛"),
(NULL,"img/forum/fh12.jpg","1安安",2,0,"最后回复于11分钟前","计划7月3日开始至7月7日逛遍古都咸阳，我开车，你负责讲故事！一起玩、逛！","2019-07-04","2019-07-07","中国、咸阳"),
(NULL,"img/forum/fh13.jpg","yeqiangweishen",3,0,"最后回复于1小时前","计划7.8到7.15到banff，jasper，yoho自驾游，需要再找个会开车","2019-07-08","2019-07-16","加拿大、温哥华、加拿大、维多利亚市"),
(NULL,"img/forum/fh14.jpg","我们应该有梦",7,0,"最后回复于1小时前","一起去西藏吗？想约个伴","2019-07-08","2019-07-31","中国、西藏"),
(NULL,"img/forum/fh15.jpg","user_hERG0NlRZ1",4,0,"最后回复于1小时前","好想找个女生一起东南亚旅游，随时可以走的。最近心情郁闷。费用可以一个人全出","2019-07-10","2019-07-18","印度尼西亚、巴厘岛"),
(NULL,"img/forum/fh16.jpg","user_yY7k0MWN7x",3,0,"最后回复于1小时前","杭州去过好几次了，没有真正的玩一次。六号到杭州，有到杭州旅行的女生吗？一起玩几天","2019-07-03","2019-07-04","中国、杭州、杭州灵隐（飞来峰）景区"),
(NULL,"img/forum/fh17.jpg","大西北旅游去",6,1,"最后回复于1小时前","七月中旬左右，青海湖，敦煌，西北大环线，六天游，有没有伙伴们一起的，约起来，私信","2019-07-12","2019-07-20","	中国、敦煌、中国、青海"),
(NULL,"img/forum/fh18.jpg","玉子GaGa",4,0,"最后回复于1小时前","7月4日-7月13日法国马赛，尼斯，巴黎。4-7宿马赛，7-10宿尼斯，10","2019-07-04","2019-07-13","法国"),
(NULL,"img/forum/fh19.jpg","user_XXvU0NlRQO",5,0,"最后回复于1小时前","大好河山，美好世界，出发","2019-07-06","2019-07-10","中国、临沂"),
(NULL,"img/forum/fh20.jpg","骑毛驴的蛋",12,1,"最后回复于1小时前","机票已出7/14到重庆 预计7/17从成都出发去色达稻城 行程预计7-8时间 拼","2019-07-14","2019-07-25","中国、成都"),
(NULL,"img/forum/fh21.jpg","凤一样的男人",4,0,"最后回复于2小时前","纽约出发，自驾游，大概2天时间，到处转转 出去散心 有兴趣的A我","2019-07-02","2019-08-01","	美国、纽约"),
(NULL,"img/forum/fh22.jpg","64956",6,0,"最后回复于2小时前","有去厦门的吗，女生19求一枚小姐妹","2019-07-03","2019-07-06","中国"),
(NULL,"img/forum/fh23.jpg","讲英语爱旅行",3,0,"最后回复于2小时前","有一起去重庆璧山摘葡萄的吗？约起来呀！周末假期，嗨起来呀！看电影，大冒险，爬山","2019-07-03","2019-07-14","	中国、重庆"),
(NULL,"img/forum/fh24.jpg","涂蘼",3,0,"最后回复于2小时前","7月21赫尔辛基回广州","2019-07-21","2019-07-22 ","	芬兰、赫尔辛基"),
(NULL,"img/forum/fh25.jpg","franshine",2,0,"最后回复于2小时前","男生一枚，家在比利时。本周六考虑荷兰一日游，自驾，求一小伙伴同行。有单反，可以一","2019-07-06","2019-07-07","荷兰、比利时"),
(NULL,"img/forum/fh26.jpg","user_4aoc0NlbPH",4,0,"最后回复于2小时前","北京大叔，近期有一段时间可以出游，想近期去泰国或者马来西亚的仙本那尼泊尔，或者其","2019-07-20","2019-07-31","	尼泊尔、泰国、清迈、马来西亚、仙本那"),
(NULL,"img/forum/fh27.jpg","Jaya_hou",6,0,"最后回复于2小时前","7.8-7.11 自驾，洛杉矶-拉斯维加斯-羚羊谷-大峡谷-洛杉矶，目前穷游已约","2019-07-08","2019-07-12","美国"),
(NULL,"img/forum/fh28.jpg","user_ryA20MwCtO",5,0,"最后回复于2小时前","越南泰国自由行，当去度假，慢慢玩，时间15天到1个月，不要国庆高峰期。","2019-08-23","2019-09-20","	泰国、越南"),
(NULL,"img/forum/fh29.jpg","user_lidr0NeSXq",3,0,"最后回复于2小时前","七月13日去缅甸仰光 浦甘 欢迎结伴呀 无论男女","2019-07-13","2019-07-21","	缅甸、缅甸、蒲甘、缅甸、仰光"),
(NULL,"img/forum/fh30.jpg","panzi0308",3,0,"最后回复于2小时前","7.8-7.10号，最主要是9号，一个人准备去卢塞恩爬山徒步，有同行的小伙伴么？","2019-07-08","2019-07-11","瑞士、卢塞恩"),
(NULL,"img/forum/fh31.jpg","想飞的毛毛",6,0,"最后回复于3小时前","2020春节期间去阿根廷、智利的有木有？计划时间为2020.01.16——202","2020-01-16","2020-01-31","阿根廷、智利"),
(NULL,"img/forum/fh32.jpg","Yuki-Lee",10,0,"最后回复于3小时前","本人女生，曾经的海岛控，东南亚海岛休闲游，时间7月-8月，机票随时可以定，不打卡","2019-07-15","2019-07-16","泰国"),
(NULL,"img/forum/fh33.jpg","陈栗子",4,0,"最后回复于3小时前","7-8月在瓦纳卡 一起滑雪吧～ 周边徒步观星也可以约","2019-07-02","2019-07-31","新西兰、瓦纳卡"),
(NULL,"img/forum/fh34.jpg","拿到驾照啦",5,0,"最后回复于3小时前","有7月5至10号左右出发川藏线小伙伴吗？一起开车AA自驾游啊。本人男，有驾照可以","2019-07-05","2019-07-10","	中国、成都、中国、西藏"),
(NULL,"img/forum/fh35.jpg","在不在不在",6,0,"最后回复于3小时前","本人男，在纽约读书，计划7月8号-14号去拉斯维加斯、洛杉矶、旧金山，已有初步行","2019-07-08","2019-07-15","美国、洛杉矶、美国、旧金山、美国、拉斯维加斯"),
(NULL,"img/forum/fh36.jpg","Ams九月",5,0,"最后回复于3小时前","很真诚的闯197国 36地区 真心求几位小伙伴 一起研究路线 做好规划 10月1","2019-07-03","2019-07-04","日本、大阪"),
(NULL,"img/forum/fh37.jpg","夏日secret",5,0,"最后回复于3小时前","2020年春节 斯里兰卡印度一个月行程 想约几个同伴一起 毕竟一个人太孤单了 三","2020-01-01","2020-01-30","印度、斯里兰卡");

/*版面列表分类表*/
CREATE TABLE traV_forum_versionClassify(
fvc_id INT PRIMARY KEY AUTO_INCREMENT,
fvc_name VARCHAR(64)
);
INSERT INTO traV_forum_versionClassify VALUES
(NULL,"穷游兴趣小组"),
(NULL,"穷游欧洲"),
(NULL,"穷游亚洲"),
(NULL,"穷游美洲"),
(NULL,"穷游大洋洲"),
(NULL,"穷游非洲"),
(NULL,"线上线下"),
(NULL,"后院");
CREATE TABLE traV_forum_versionInfo(
  fvi_id INT PRIMARY KEY AUTO_INCREMENT,
  fvc_id INT,
  fvi_Pic VARCHAR(256),
  fvi_title VARCHAR(64),
  fvi_info VARCHAR(128)
);
INSERT INTO traV_forum_versionInfo VALUES
(NULL,1,"img/forum/b1_1.png","结伴同游","一起穷游到老!"),
(NULL,1,"img/forum/b1_2.png","签证","出境旅行的第一步"),
(NULL,1,"img/forum/b1_3.png","保险","旅行保险交流"),
(NULL,1,"img/forum/b1_4.png","旅行购物","喜刷刷喜刷刷"),
(NULL,1,"img/forum/b1_5.png","穷游折扣","旅行特价集散地"),
(NULL,1,"img/forum/b1_6.png","睡遍全球","带你免费体验全球酒店"),
(NULL,1,"img/forum/b1_7.png","邮轮","慢游的享受"),
(NULL,1,"img/forum/b1_8.png","航空","追求高性价比的机票和航程"),
(NULL,1,"img/forum/b1_9.png","自驾","心有多宽路就有多远"),
(NULL,1,"img/forum/b1_10.png","旅行视频","用影像去记录旅行"),
(NULL,1,"img/forum/b1_11.png","旅行摄影","行色"),
(NULL,1,"img/forum/b1_12.png","户外运动","体验即生活"),
(NULL,1,"img/forum/b1_13.png","潜水俱乐部","我们属于那一片深蓝"),
(NULL,1,"img/forum/b1_14.png","带孩子旅行","培养穷游er第二代"),
(NULL,1,"img/forum/b1_15.png","带父母旅行","关注带父母出游的方方面面"),
(NULL,1,"img/forum/b1_16.png","明信片","全球最大的华人明信片交换平台"),
(NULL,1,"img/forum/b1_17.png","路刻社","复刻旅行时光"),
(NULL,1,"img/forum/b1_18.png","Discovery探索频道","探索世界的已知和未知"),
(NULL,2,"img/forum/b2_1.png","环游欧洲","欧洲跨国长途旅行"),
(NULL,2,"img/forum/b2_2.png","法国/摩纳哥","浪漫就在身边"),
(NULL,2,"img/forum/b2_3.png","德国","穷游诞生地！"),
(NULL,2,"img/forum/b2_4.png","瑞士/列支敦士登","上帝的后花园"),
(NULL,2,"img/forum/b2_5.png","奥地利","喜欢莫扎特还是更爱维也纳猪排"),
(NULL,2,"img/forum/b2_6.png","捷克/斯洛伐克/匈牙利","波西米亚与多瑙河"),
(NULL,2,"img/forum/b2_7.png","西班牙/葡萄牙/安道尔","大航海、弗拉门戈和白色小镇"),
(NULL,2,"img/forum/b2_8.png","希腊/塞浦路斯","西方文明的起源"),
(NULL,2,"img/forum/b2_9.png","意大利/梵蒂冈/圣马力诺/马耳他","爱速度还是爱披萨？"),
(NULL,2,"img/forum/b2_10.png","英国/爱尔兰","Fish&Chips or U2"),
(NULL,2,"img/forum/b2_11.png","荷兰/比利时/卢森堡","郁金香、奶酪还有丁丁历险记"),
(NULL,2,"img/forum/b2_12.png","波兰/立陶宛/拉脱维亚/爱沙尼亚","波罗的海"),
(NULL,2,"img/forum/b2_13.png","挪威/瑞典/芬兰/丹麦/冰岛","圣诞老人、海盗传说、童话故事当然还有极光"),
(NULL,2,"img/forum/b2_14.png","俄罗斯/乌克兰/白俄罗斯","战斗民族"),
(NULL,2,"img/forum/b2_15.png","外高加索三国","高加索山脉南麓"),
(NULL,2,"img/forum/b2_16.png","土耳其","链接欧亚大陆"),
(NULL,2,"img/forum/b2_17.png","东南欧地区","黑海与亚得里亚海间的明珠们"),
(NULL,2,"img/forum/b2_18.png","欧洲交通","在欧洲，便利的出行方式选择多多"),
(NULL,3,"img/forum/b3_1.png","环游亚洲","亚洲跨国长途旅行"),
(NULL,3,"img/forum/b3_2.png","日本","樱花与刺身"),
(NULL,3,"img/forum/b3_3.png","韩国/朝鲜","韩剧、泡菜、领袖"),
(NULL,3,"img/forum/b3_4.png","台湾","很多美食的宝岛"),
(NULL,3,"img/forum/b3_5.png","香港/澳门","东方之珠"),
(NULL,3,"img/forum/b3_6.png","泰国","冬荫功汤、四面佛和国王"),
(NULL,3,"img/forum/b3_7.png","马来西亚/文莱","狮身鱼尾、肉骨茶和双子塔"),
(NULL,3,"img/forum/b3_8.png","新加坡","海南鸡饭与鱼尾狮"),
(NULL,3,"img/forum/b3_9.png","菲律宾","离中国最近的热带海岛"),
(NULL,3,"img/forum/b3_10.png","柬埔寨","吴哥的微笑"),
(NULL,3,"img/forum/b3_11.png","越南","湄公河、奥黛和米粉"),
(NULL,3,"img/forum/b3_12.png","老挝","寺庙、僧侣和慢节奏"),
(NULL,3,"img/forum/b3_13.png","缅甸","多少云烟佛塔"),
(NULL,3,"img/forum/b3_14.png","尼泊尔","让喜马拉雅山去改变你"),
(NULL,3,"img/forum/b3_15.png","不丹","雷龙之国"),
(NULL,3,"img/forum/b3_16.png","印度尼西亚/东帝汶","此巴厘不是彼巴黎"),
(NULL,3,"img/forum/b3_17.png","马尔代夫","椰林树影水清沙幼"),
(NULL,3,"img/forum/b3_18.png","斯里兰卡","印度洋上的眼泪"),
(NULL,3,"img/forum/b3_19.png","印度/孟加拉","神牛、神油、神庙"),
(NULL,3,"img/forum/b3_20.png","伊朗","左手伊朗 右手波斯"),
(NULL,3,"img/forum/b3_21.png","巴基斯坦/阿富汗","战后的家园"),
(NULL,3,"img/forum/b3_22.png","阿联酋/卡塔尔","土豪国的传说"),
(NULL,3,"img/forum/b3_23.png","以色列","圣城与纷争"),
(NULL,3,"img/forum/b3_24.png","西亚其他国家","说不清"),
(NULL,3,"img/forum/b3_25.png","中亚各国","各种斯坦和草原"),
(NULL,3,"img/forum/b3_26.png","蒙古","套马的汉子"),
(NULL,3,"img/forum/b3_27.png","中国内地","你懂的！"),
(NULL,4,"img/forum/b4_1.png","美国","多元、都市和自然"),
(NULL,4,"img/forum/b4_2.png","加拿大","枫叶、落基山与冰地"),
(NULL,4,"img/forum/b4_3.png","中美","玛雅文明、朗姆酒与加勒比海"),
(NULL,4,"img/forum/b4_4.png","南美/南极","足球、桑巴、狂欢节和世界尽头"),
(NULL,5,"img/forum/b5_1.png","澳大利亚","袋鼠、考拉和大石头"),
(NULL,5,"img/forum/b5_2.png","新西兰","魔戒在净土"),
(NULL,5,"img/forum/b5_3.png","太平洋海岛","大洋中的世外桃源"),
(NULL,6,"img/forum/b6_1.png","北非地区","沙漠、神秘和古文明"),
(NULL,6,"img/forum/b6_2.png","东非地区","动物世界"),
(NULL,6,"img/forum/b6_3.png","非洲海岛","不一样的浪漫非洲"),
(NULL,6,"img/forum/b6_4.png","非洲其他国家","雨林和部落"),
(NULL,7,"img/forum/b7_1.png","穷游活动","线上及线下活动"),
(NULL,7,"img/forum/b7_2.png","穷游er访谈","穷游er专栏, 原长老访谈录"),
(NULL,7,"img/forum/b7_3.png","穷游沙龙","穷游沙龙专版"),
(NULL,7,"img/forum/b7_4.png","轻年计划","大学生海外旅行奖学金计划"),
(NULL,7,"img/forum/b7_5.png","城市漫步","认识一座城市最好的方式"),
(NULL,8,"img/forum/b8_1.png","海阔天空","没有严格的话题归类, 请尽量围绕自助旅行讨论"),
(NULL,8,"img/forum/b8_2.png","转让专区","转让旅行相关商品");

/*行程助手中头部的数据*/
CREATE TABLE traV_helper_classify(
  hc_id INT PRIMARY KEY AUTO_INCREMENT,
  hc_clname VARCHAR(64)
);
INSERT INTO traV_helper_classify VALUES
(NULL,"目的地"),
(NULL,"出行时间"),
(NULL,"出行天数"),
(NULL,"出发城市"),
(NULL,"行程主题"),
(NULL,"精华等级");

CREATE TABLE traV_helper_classifyInfo(
  hci_id INT PRIMARY KEY AUTO_INCREMENT,
  hc_id INT,
  hci_name VARCHAR(64)
);
INSERT INTO traV_helper_classifyInfo VALUES
(NULL,1,"中国"),
(NULL,1,"泰国"),
(NULL,1,"日本"),
(NULL,1,"法国"),
(NULL,1,"美国"),
(NULL,1,"韩国"),
(NULL,1,"马来西亚"),
(NULL,1,"意大利"),
(NULL,1,"新加坡"),
(NULL,1,"德国"),
(NULL,1,"西班牙"),
(NULL,1,"英国"),
(NULL,2,"一月"),
(NULL,2,"二月"),
(NULL,2,"三月"),
(NULL,2,"四月"),
(NULL,2,"五月"),
(NULL,2,"六月"),
(NULL,2,"七月"),
(NULL,2,"八月"),
(NULL,2,"九月"),
(NULL,2,"十月"),
(NULL,2,"十一月"),
(NULL,2,"十二月"),
(NULL,2,"新年"),
(NULL,3,"3天及以下"),
(NULL,3,"4天至7天"),
(NULL,3,"8天至14天"),
(NULL,3,"14天至20天"),
(NULL,3,"20天以上"),
(NULL,4,"北京"),
(NULL,4,"上海"),
(NULL,4,"广州"),
(NULL,4,"深圳"),
(NULL,4,"重庆"),
(NULL,4,"成都"),
(NULL,4,"杭州"),
(NULL,4,"香港"),
(NULL,5,"美食"),
(NULL,5,"人文"),
(NULL,5,"购物"),
(NULL,5,"游园"),
(NULL,5,"观光"),
(NULL,5,"娱乐"),
(NULL,5,"休闲"),
(NULL,5,"沙滩"),
(NULL,5,"海岛"),
(NULL,5,"户外"),
(NULL,5,"自然风光"),
(NULL,5,"自驾"),
(NULL,5,"蜜月"),
(NULL,5,"亲子"),
(NULL,6,"一级精华"),
(NULL,6,"二级精华"),
(NULL,6,"三级精华");
/*主体内容*/
CREATE TABLE traV_helper_contentInfo(
  hco_id INT PRIMARY KEY AUTO_INCREMENT,
  hco_days INT,
  hco_goTime VARCHAR(64),
  hco_title VARCHAR(64),
  hco_theme1 VARCHAR(32),
  hco_theme2 VARCHAR(32),
  hco_places VARCHAR(256),
  hco_pname VARCHAR(128),
  hco_lookcount INT,
  hco_replaycount INT,
  hco_pic VARCHAR(256)
);
INSERT INTO traV_helper_contentInfo VALUES
(NULL,48,"2024-09-01 出发","法国（签证版）","购物","美食","广州·巴黎·凡尔赛·阿维尼翁·马赛·尼斯·戛纳·里昂·格勒诺布尔·日内瓦·菲斯普·采尔马特·卢塞恩·苏黎世·阿姆斯特丹·羊角村·海牙·鹿特丹·吉维尼·圣米歇尔山·图尔·昂布瓦兹·波尔多·图卢兹·卡尔卡松·蒙彼利埃·阿尔勒","Findingiris",46393,153,"img/helper/c1.jpg"),
(NULL,21,"2019-09-09 出发","罗马进米兰出（含瑞士）","购物","美食","北京·罗马·梵蒂冈·Civita di Bagnoregio·奥尔维耶托·维泰尔博·锡耶纳·圣吉米亚诺·比萨·卢卡·五渔村·佛罗伦萨·圣马力诺市·里米尼·威尼斯·多洛米蒂山脉·菲森·施泰因·苏黎世·韦吉斯·卢塞恩·龙疆·劳特布龙嫩·米伦·文根·格林德瓦·施皮茨·伯尔尼·洛桑·日内瓦·阿讷西·依云·塔什·采尔马特·米兰","gjkkkkkk",3070,84,"img/helper/c2.jpg"),
(NULL,12,"2026-03-01 出发","巴黎罗马巴塞罗那","","","香港·上海·巴黎·罗马·梵蒂冈·巴塞罗那","Findingiris",5375,100,"img/helper/c3.jpg"),
(NULL,10,"2019-07-13 出发","北海道计划书19年方案","美食","","新加坡·札幌·函馆·洞爷湖·室兰·小樽·旭川·美瑛·富良野","流青",1974,87,"img/helper/c4.jpg"),
(NULL,13,"2020-09-26 出发","魔芋菌的奥捷行程","购物","","北京·布拉格·库特纳霍拉·捷克克鲁姆洛夫·萨尔茨堡·哈尔施塔特·维也纳","魔芋菌",2366,84,"img/helper/c5.jpg"),
(NULL,11,"2019-12-12 出发","新西兰南岛自驾行","购物","自驾","上海·广州·基督城·库克山镇·蒂卡普湖·库克山国家公园·瓦纳卡·箭镇·皇后镇·格林诺奇·弗朗茨约瑟夫冰川·霍基蒂卡·亚瑟山口国家公园·格雷茅斯·凯库拉","天道未明",1213,47,"img/helper/c6.jpg"),
(NULL,10,"2019-08-09 出发","瑞士10日行程","购物","美食","日内瓦·洛桑·蒙特勒·谢布尔·沃韦·格吕耶尔·弗里堡·伯尔尼·图恩·施皮茨·因特拉肯·茵诺科琴·卢塞恩·苏黎世","渣渣c7h5o6n3",1823,49,"img/helper/c7.jpg"),
(NULL,25,"2019-07-19 出发","遇见童话-意大利","","","北京·罗马·梵蒂冈·皮恩扎·圣奎里科多尔恰·蒙塔尔奇诺·沃尔泰拉·圣吉米亚诺·阿雷佐·科尔托纳·蒙特普尔恰诺·比萨·卢卡·锡耶纳·佛罗伦萨·维罗纳·西尔米奥奈·加尔达·多洛米蒂山脉·巴迪亚谷·加尔代纳谷·博尔扎诺·科尔瓦拉·法萨谷·科尔蒂纳丹佩佐·休斯山·科莫·贝拉吉奥·瓦伦纳·米兰","遇见童话",7078,267,"img/helper/c8.jpg"),
(NULL,10,"2019-07-10 出发","澳大利亚定制参考路线","购物","美食","杭州·墨尔本·托尔坎镇·阿波罗小镇·大洋路·坎贝尔港国家公园·悉尼·澳大利亚蓝山","易途吧旅行管家",1222,71,"img/helper/c9.jpg"),
(NULL,9,"2019-09-07 出发","希腊9日行程","","","北京·雅典·科林斯·纳夫普利奥·斯巴达·奥林匹亚·扎金索斯·圣托里尼","渣渣c7h5o6n3",926,33,"img/helper/c10.jpg"),
(NULL,8,"2019-08-19 出发","梦中的贝加尔湖（路线1）","","","上海·伊尔库茨克·奥尔洪岛·贝加尔湖·利斯特维扬卡","酉酉051223",2827,61,"img/helper/c11.jpg"),
(NULL,50,"2024-08-01 出发","法国（签证版）2","","","广州·巴黎·凡尔赛·阿维尼翁·马赛·尼斯·戛纳·里昂·格勒诺布尔·布鲁日·根特·布鲁塞尔·卢森堡市·阿姆斯特丹·羊角村·海牙·鹿特丹·吉维尼·圣米歇尔山·图尔·昂布瓦兹·波尔多·图卢兹·卡尔卡松·蒙彼利埃·阿尔勒","Findingiris",600,24,"img/helper/c12.jpg"),
(NULL,12,"2020-08-01 出发","湖南之旅","","","成都·长沙·凤凰·湘西·张家界市·张家界风景区","Valueforth",1190,70,"img/helper/c13.jpg"),
(NULL,16,"2019-09-21 出发","qld139113的波兰九日游线路","","","北京·华沙·波兰马尔堡·格但斯克·索波特·托伦·弗罗茨瓦夫·布拉格·克拉科夫·捷克克鲁姆洛夫·维也纳·布拉迪斯拉发·泰尔奇·奥洛莫茨","qld139113",1488,19,"img/helper/c14.jpg"),
(NULL,10,"2025-07-16 出发","英国-伦敦-爱丁堡-温莎-巴斯","购物","美食","上海·伦敦·牛津·剑桥·爱丁堡·苏格兰高地·苏格兰·因弗尼斯·尼斯湖·威廉堡·巴斯·巨石阵","柚子_柚子",6139,356,"img/helper/c15.jpg"),
(NULL,15,"2019-10-19 出发","2019加拿大赏枫之旅","","美食","上海·多伦多·亨茨维尔·阿岗昆·渥太华·蒙特朗布朗·魁北克市·蒙特利尔·加纳诺克·加拿大金斯顿·尼亚加拉湖滨小镇·加拿大尼亚加拉瀑布城·密西沙加","绿萝music",2217,129,"img/helper/c16.jpg"),
(NULL,14,"2023-09-26 出发","新西兰自驾南岛深度游","美食","自驾","上海·奥克兰·新西兰马尔堡·凯库拉·基督城·格雷茅斯·普纳凯基·霍基蒂卡·弗朗茨约瑟夫冰川·福克斯冰川·瓦纳卡·箭镇·皇后镇·蒂阿瑙·因弗卡吉尔·奥瓦卡·但尼丁·奥马鲁·怀马蒂·特威泽尔·阿卡罗阿","taogeww",4001,161,"img/helper/c17.jpg"),
(NULL,18,"2019-07-03 出发","2019年暑假加拿大西线及西雅图自驾游","美食","自驾","上海·卡尔加里·班夫镇·班夫国家公园·库特内国家公园·幽鹤国家公园·贾斯珀国家公园·温哥华·西雅图","皓月流光",2664,96,"img/helper/c18.jpg"),
(NULL,28,"2019-07-07 出发","作光和盐的美国行程","购物","美食","上海·洛杉矶·旧金山·波特兰·西雅图·优胜美地国家公园·拉斯维加斯·大峡谷国家公园·佩吉市·黄石国家公园·圣迭戈·波士顿·纽黑文·费城·美国尼亚加拉瀑布城·芝加哥·华盛顿·纽约","作光和盐",403,15,"img/helper/c19.jpg"),
(NULL,14,"2019-09-29 出发","2019国庆瑞士行程","购物","美食","北京·苏黎世·洛桑·依云·蒙特勒·沃韦·采尔马特·因特拉肯·格林德瓦·文根·劳特布龙嫩·米伦·施皮茨·坎德施泰格·布里恩茨·卢塞恩·龙疆","流泪de球球",725,14,"img/helper/c20.jpg"),
(NULL,12,"2020-08-01 出发","巫文馨的穷游之旅","","","成都·香格里拉·丽江·大理·喜洲·昆明","巫文馨",372,31,"img/helper/c21.jpg"),
(NULL,9,"2019-07-06 出发","魔芋菌的西班牙&尼斯行程","购物","","北京·迪拜·尼斯·圣保罗·德·旺斯·瓦朗索尔·穆斯捷-圣玛丽·普罗旺斯·埃兹·摩纳哥·马赛·巴塞罗那·赫罗纳","魔芋菌",386,16,"img/helper/c22.jpg"),
(NULL,9,"2019-11-07 出发","Jooc的新西兰行程","","","上海·基督城·福克斯冰川·瓦纳卡·皇后镇·蒂阿瑙·但尼丁·蒂卡普湖·库克山国家公园","Jooc",122,15,"img/helper/c23.jpg"),
(NULL,25,"2019-07-13 出发","Akira的新西兰三刷行程","购物","美食","天津·奥克兰·基督城·格雷茅斯·霍基蒂卡·瓦纳卡·皇后镇·格林诺奇·图阿塔皮里·因弗卡吉尔·布拉夫·斯图尔特岛·卡特琳斯·但尼丁·特威泽尔·蒂卡普湖·尼尔森·亚伯塔斯曼国家公园·皮克顿·惠灵顿·内皮尔·陶朗阿·派希亚·旺格雷","AkiraHaku",415,10,"img/helper/c24.jpg"),
(NULL,19,"2019-07-17 出发","捷奥匈","购物","美食","成都·布拉格·捷克克鲁姆洛夫·圣沃尔夫冈·巴德依舍·哈尔施塔特·梅尔克·都因斯坦·多瑙河畔克雷姆斯·维也纳·布达佩斯·圣安德烈","mickeygong001",686,26,"img/helper/c25.jpg"),
(NULL,15,"2020-03-16 出发","砒霜蝴蝶的俄罗斯行程","","","上海·莫斯科·摩尔曼斯克·捷里别尔卡·圣彼得堡·伊尔库茨克·利斯特维扬卡","砒霜蝴蝶",350,10,"img/helper/c26.jpg"),
(NULL,14,"2020-09-23 出发","小肠子的新西兰15日自驾","购物","美食","重庆·新加坡·基督城·蒂卡普湖·新西兰南岛·库克山国家公园·特威泽尔·瓦纳卡·箭镇·皇后镇·格林诺奇·蒂阿瑙·但尼丁·奥马鲁","小肠子",280,12,"img/helper/c27.jpg"),
(NULL,11,"2019-10-16 出发","2019未未出国行第一弹-冲绳","沙滩海岛","美食","上海·冲绳市·那霸·名護市·冲绳·丰见城市·南城市","guiguilin",410,7,"img/helper/c28.jpg"),
(NULL,40,"2020-07-10 出发","2020年长辈欧洲游","","","广州·奥斯陆·吕瑟峡湾·哈当厄尔峡湾·松恩峡湾·特罗姆瑟·盖朗厄尔峡湾·卑尔根·阿姆斯特丹·布鲁塞尔·巴黎·哥本哈根·柏林·法兰克福·海德堡·慕尼黑·苏黎世·日内瓦·米兰·五渔村·威尼斯·佛罗伦萨·罗马","user_dUD6T1LHiR",254,2,"img/helper/c29.jpg"),
(NULL,15,"2020-01-01 出发","粉色爱紫色的德国行程","购物","美食","上海·慕尼黑·加米施-帕腾基兴·萨尔茨堡·巴德哥依斯恩·哈尔施塔特·贝希特斯加登·林道·康斯坦茨","粉色爱紫色",210,6,"img/helper/c30.jpg"),
(NULL,12,"2024-07-10 出发","夏威夷参考行程","","","成都·上海·檀香山·毛伊岛·夏威夷大岛·瓦胡岛","jigen888",49,2,"img/helper/c31.jpg"),
(NULL,9,"2027-09-15 出发","意大利南部行程","美食","","北京·伊斯坦布尔·罗马·那不勒斯·阿马尔菲·卡普里岛·帕勒莫·阿格里真托·锡拉库萨·卡塔尼亚","渣渣c7h5o6n3",132,4,"img/helper/c32.jpg"),
(NULL,14,"2020-01-26 出发","澳大利亚亲子","购物","亲子","上海·墨尔本·香港·吉朗·托尔坎镇·龙恩·阿波罗小镇·坎贝尔港国家公园·大洋路·沃南布尔·悉尼·黄金海岸·布里斯班","suidge",366,14,"img/helper/c33.jpg"),
(NULL,8,"2020-01-22 出发","孙小蕾童鞋的日本行程","购物","美食","上海·札幌·富良野·旭川·小樽·登别","孙小蕾童鞋",133,3,"img/helper/c34.jpg"),
(NULL,9,"2021-02-16 出发","2018缅甸八日","购物","","大连·仰光·曼德勒·蒲甘·首尔","greatfish",377,3,"img/helper/c35.jpg"),
(NULL,10,"2024-09-01 出发","加拿大（签证版）","","","广州·多伦多·尼亚加拉瀑布城·渥太华·蒙特利尔·魁北克市","Findingiris",64,3,"img/helper/c36.jpg"),
(NULL,20,"2024-07-10 出发","史蒂夫的事的瑞典丹麦芬兰挪威冰岛行程","","","嘉兴·赫尔辛基·罗瓦涅米·斯德哥尔摩·哥本哈根·奥斯陆·雷克雅未克·阿克雷里·米湖·赫本·维克","史蒂夫的事",128,1,"img/helper/c37.jpg"),
(NULL,17,"2019-07-30 出发","黑白素描的法国行程","购物","美食","北京·巴黎·吉维尼·埃特勒塔·卢瓦尔河谷·布洛瓦·波尔多·图卢兹·尼姆·阿讷西·科尔马·圣米歇尔山·凡尔赛","黑白素描",58,1,"img/helper/c38.jpg"),
(NULL,20,"2024-07-25 出发","皮皮岁的冰岛土耳其英国行程","","","上海·雷克雅未克·维克·赫本·米湖·阿克雷里·伦敦·曼彻斯特·利物浦·伊斯坦布尔·格雷梅·卡帕多西亚·安塔利亚·棉花堡·以弗所·伊兹密尔","皮皮岁",107,1,"img/helper/c39.jpg"),
(NULL,28,"2023-08-20 出发","行走的童年Season4B_北美","购物","美食","哈尔滨·纽约·普林斯顿·新泽西州·费城·华盛顿·芝加哥·水牛城·美国尼亚加拉瀑布城·加拿大尼亚加拉瀑布城·多伦多·渥太华·蒙特利尔·波士顿·马萨诸塞州·北京","格雅依旅",312,1,"img/helper/c40.jpg"),
(NULL,12,"2019-11-15 出发","BlairChen88的澳大利亚行程","","","上海·墨尔本·大洋路·吉朗·阿波罗小镇·坎贝尔港国家公园·塔斯马尼亚岛·菲利普岛·黄金海岸·布里斯班·悉尼","BlairChen88",190,2,"img/helper/c41.jpg"),
(NULL,15,"2020-01-11 出发","惟安然的英国冰岛行程","","","上海·伦敦·雷克雅未克·维克·瓦特纳冰川国家公园·赫本·selfoss·斯蒂基斯霍尔米·凯夫拉维克·巴斯·巨石阵","惟安然",190,2,"img/helper/c42.jpg"),
(NULL,15,"2019-12-27 出发","老虎咪咪的西班牙行程","","","上海·马德里·塞哥维亚·塞维利亚·科尔多瓦·马拉加·西班牙龙达·格拉纳达·巴塞罗那·瓦伦西亚·巴黎","老虎咪咪",217,3,"img/helper/c43.jpg"),
(NULL,15,"2020-09-23 出发","新西兰15日游（非自驾）","","","重庆·新加坡·基督城·蒂卡普湖·新西兰南岛·库克山国家公园·瓦纳卡·皇后镇·箭镇·格林诺奇·蒂阿瑙·但尼丁·奥马鲁","小肠子",142,3,"img/helper/c44.jpg"),
(NULL,13,"2019-09-12 出发","2019年9月冰島自駕遊","","","香港·赫尔辛基·哥本哈根·雷克雅未克·维克·瓦特纳冰川国家公园·赫本·米湖·阿克雷里","Happy_Lo",195,2,"img/helper/c45.jpg"),
(NULL,24,"2023-01-30 出发","行走的童年Season4A_美西","购物","沙滩海岛","哈尔滨·西雅图·盐湖城·杰克逊·大峡谷国家公园·拉斯维加斯·优胜美地国家公园·旧金山·洛杉矶·檀香山·毛伊岛·夏威夷大岛","格雅依旅",88,0,"img/helper/c46.jpg"),
(NULL,24,"2027-02-03 出发","行走的童年Season8A_华南","美食","","哈尔滨·桂林·龙脊梯田·阳朔·普者黑·昆明·西双版纳·大理·丽江·香格里拉·泸沽湖","格雅依旅",106,0,"img/helper/c47.jpg"),
(NULL,21,"2021-08-01 出发","再考虑下","","","珀斯·新加坡·莫斯科·斯德哥尔摩·奥斯陆·弗洛姆·松恩峡湾·艾于兰·卑尔根·努尔黑姆松·哈当厄尔峡湾·奥达·斯塔万格·吕瑟峡湾·奥胡斯·哥本哈根·赫尔辛格·赫尔辛堡·马尔默","疯牛洒妈",57,0,"img/helper/c48.jpg"),
(NULL,26,"2020-10-01 出发","智锅的德国英国行程","","","成都·慕尼黑·菲森·海德堡·罗滕堡·维尔茨堡·乌尔姆·科布伦茨·巴登-巴登·黑森林·林道·康斯坦茨·浪漫之路·加米施-帕腾基兴·伦敦·剑桥·约克·尼斯湖·苏格兰高地·天空之岛·爱丁堡·谢菲尔德·埃文河畔斯特拉福德·巴斯·牛津","智锅",75,0,"img/helper/c49.jpg"),
(NULL,14,"2020-10-01 出发","智锅的德国行程","","","成都·法兰克福·海德堡·黑森林·菲森·慕尼黑·贝希特斯加登·罗滕堡·维尔茨堡·纽伦堡·德累斯顿·柏林·巴拿马科隆","智锅",38,0,"img/helper/c50.jpg"),
(NULL,20,"2019-07-09 出发","奈酱Poi的美国行程","","","成都·洛杉矶·西雅图·加利福尼亚州蒙特雷·黄石国家公园·费城·纽约·华盛顿·拉斯维加斯","奈酱Poi",55,0,"img/helper/c51.jpg"),
(NULL,9,"2019-11-22 出发","京都世界文化遗产之旅","购物","美食","北京·京都","hpglbn",70,0,"img/helper/c52.jpg"),
(NULL,10,"2020-02-03 出发","以色列+约旦","","","北京·特拉维夫·海法·阿卡·提比利亚·约旦死海·安曼·杰拉什·佩特拉·瓦迪拉姆·耶路撒冷","我要多吃肉",98,1,"img/helper/c53.jpg"),
(NULL,18,"2019-08-01 出发","8月冰岛行程","","","北京·雷克雅未克·塞尔福斯Selfoss·海德拉·hella 海拉·韦斯特曼纳群岛·HELLA·维克·Kirkjubæjarklaustur教堂镇·瓦特纳冰川国家公园·赫本·都皮沃古尔·布雷兹达斯湾·塞济斯菲厄泽Seyðisfjörður·埃伊尔斯塔济·胡萨维克·雷恰利兹Reyksjshlid·米湖·阿克雷里·华姆斯唐吉·Laugarbakki·Patreksfjordur·布辽斯莱库·斯蒂基斯霍尔米·Borgarnes··广州","AkiraHaku",118,0,"img/helper/c54.jpg"),
(NULL,14,"2020-09-28 出发","橘子的家的美国行程","","","上海·纽约·波士顿·美国尼亚加拉瀑布城·洛杉矶·旧金山","橘子的家",81,0,"img/helper/c55.jpg"),
(NULL,11,"2019-07-05 出发","遲遲玫瑰露的保加利亚塞尔维亚俄罗斯行程","","","上海·索菲亚·玫瑰山谷·贝尔格莱德·莫斯科·圣彼得堡","遲遲玫瑰露",211,0,"img/helper/c56.jpg"),
(NULL,16,"2022-07-02 出发","西夏小小的爱尔兰行程","购物","美食","成都·都柏林·高威·基尔代尔郡·威克洛郡·科克·丁格尔·利默里克·恩尼斯·斯莱戈·多尼戈尔·康内马拉","西夏小小",182,0,"img/helper/c57.jpg"),
(NULL,16,"2020-01-01 出发","世界就一个我的马来西亚土耳其行程","","","海口·吉隆坡·北海·古晋·马六甲·伊斯坦布尔·格雷梅·卡帕多西亚·安塔利亚·棉花堡·以弗所·伊兹密尔","世界就一个我",126,0,"img/helper/c58.jpg"),
(NULL,16,"2020-01-01 出发","我是老崔的欧洲行","","","北京·巴黎·凡尔赛·阿姆斯特丹·安特卫普·Boom·boom·布鲁塞尔·因特拉肯·布里恩茨·佛罗伦萨·比萨·罗马·圣托里尼","我是老崔",155,3,"img/helper/c59.jpg"),
(NULL,14,"2020-09-26 出发","copy英国","","","上海·伦敦·温莎·剑桥·牛津·科茨沃尔德·水上伯顿·英国湖区·格拉斯哥·洛蒙德湖与特罗萨克斯山国家公园·苏格兰高地·威廉堡·奥本·爱丁堡","shhenry",75,1,"img/helper/c60.jpg"),
(NULL,16,"2019-09-21 出发","新西兰南岛计划16天","","","北京·基督城·凯库拉·格雷茅斯·普纳凯基·福克斯冰川·霍基蒂卡·瓦纳卡·皇后镇·蒂阿瑙·格林诺奇·克伦威尔·特威泽尔·库克山镇·库克山国家公园·蒂卡普湖·新西兰南岛","假模假样",75,0,"img/helper/c61.jpg"),
(NULL,10,"2019-09-21 出发","新西兰自驾（样例行程）","购物","美食","广州·基督城·格雷茅斯·普纳凯基·霍基蒂卡·弗朗茨约瑟夫冰川·福克斯冰川·瓦纳卡·箭镇·皇后镇·奥克兰·上海","samanthayang",21,0,"img/helper/c62.jpg"),
(NULL,13,"2028-07-10 出发","行走的童年Season9B_中原","","","哈尔滨·大同·太原·晋中·平遥·咸阳·西安·华山·洛阳·武汉·南昌·岳阳·长沙·张家界风景区·凤凰","格雅依旅",75,0,"img/helper/c63.jpg"),
(NULL,12,"2019-07-26 出发","aliceinchain的成都行程","","","杭州·成都·青城山·都江堰·四姑娘山·丹巴·新都桥·雅江·理塘·稻城·香格里拉镇·香格里拉·亚丁神山","aliceinchain",138,0,"img/helper/c64.jpg"),
(NULL,17,"2019-07-30 出发","黑白素描的法国行程","购物","美食","北京·巴黎·吉维尼·埃特勒塔·卢瓦尔河谷·布洛瓦·波尔多·图卢兹·尼姆·阿讷西·科尔马·圣米歇尔山·凡尔赛","黑白素描",132,8,"img/helper/c65.jpg"),
(NULL,23,"2020-01-26 出发","新西兰（南岛）自由行","","","厦门·奥克兰·基督城·凯库拉·布兰尼姆·新西兰马尔堡·皮克顿·格雷茅斯·霍基蒂卡·福克斯冰川·瓦纳卡·箭镇·皇后镇·格林诺奇·蒂阿瑙·米尔福德峡湾·因弗卡吉尔·古董湾·卡特琳斯·但尼丁·奥马鲁·蒂卡普湖·汤加里罗国家公园·罗托鲁阿·玛塔玛塔·香港·深圳","18970055192",420,1,"img/helper/c66.jpg"),
(NULL,18,"2019-07-30 出发","黑白素描的法国行程","","","北京·巴黎·凡尔赛·圣米歇尔山·卢瓦尔河谷·枫丹白露·里昂·波尔多·图卢兹·卡尔卡松·蒙彼利埃·阿尔勒·格勒诺布尔·阿讷西·科尔马·第戎","raisonliu1992",45,0,"img/helper/c67.jpg"),
(NULL,14,"2019-07-30 出发","黑白素描的法国行程","","","北京·巴黎·凡尔赛·圣米歇尔山·卢瓦尔河谷·枫丹白露·里昂·波尔多·图卢兹·卡尔卡松·蒙彼利埃·阿尔勒·格勒诺布尔·阿讷西·科尔马·第戎","黑白素描",55,0,"img/helper/c68.jpg"),
(NULL,6,"2019-10-02 出发","karen945的日本行程","","","上海·大阪·奈良·京都","karen945",36,0,"img/helper/c69.jpg"),
(NULL,9,"2019-12-14 出发","Masterlumo的日本行程","","","广州·东京·札幌·旭川·小樽·洞爷湖·登别·函馆","Masterlumo",61,0,"img/helper/c70.jpg"),
(NULL,6,"2030-10-01 出发","十一长白山金秋","","","北京·盘锦·沈阳·长白山·延吉·吉林市·长春","YAY狙击之狼",144,6,"img/helper/c71.jpg"),
(NULL,9,"2019-10-01 出发","raisonliu1992的德国行程","","","上海·慕尼黑·菲森·苏黎世·英格堡·卢加诺·米兰·威尼斯·锡耶纳·罗马","raisonliu1992",36,0,"img/helper/c72.jpg");

/*商品列表数据*/
CREATE TABLE traV_products_list(
  tp_id INT PRIMARY KEY AUTO_INCREMENT,
  tp_calid INT,
  tp_pic VARCHAR(256),
  tp_detail VARCHAR(256),
  tp_price DECIMAL(8,2),
  tp_info VARCHAR(32),
  tp_clName VARCHAR(32)
);
INSERT INTO traV_products_list VALUES
(NULL,1,"img/products/floor1/p1.jpg","天津往返东京/大阪/名古屋/冲绳/札幌4-7天含税机票（大阪赠机场免税店电子折扣券/天津航空/日本航空/中国航空/A点进B点出+299得3年多次签证）",999,"",""),
(NULL,1,"img/products/floor1/p2.jpg","【暑期热售】上海/无锡/杭州/宁波直飞澳门3-7天往返含税机票 (品质东航+天数可选+20KG免费行李)",899,"",""),
(NULL,1,"img/products/floor1/p3.png","[暑期特惠]广州/深圳/中山/东莞往返东京/大阪5-16天往返含税机票（赠送各地码头往返香港船票+可缺口行程）",2599,"",""),
(NULL,1,"img/products/floor1/p4.png","[暑期]成都/重庆直飞清迈5-6天往返含税机票(包机航班+可代办签证+可自由搭配酒店自由行)",1399,"",""),
(NULL,1,"img/products/floor1/p5.png","新加坡滨海湾花园电子兑换券(花穹&云雾林双园)", 88,"",""),
(NULL,1,"img/products/floor1/p6.jpg","新西兰南岛神奇峡湾游艇自然探索一日游(皇后镇/蒂阿瑙/游船码头可选）",341,"",""),
(NULL,1,"img/products/floor1/p7.jpg","【冰雪奇缘】新西兰福克斯冰川直升机徒步/攀冰体验/峡谷徒步",2002,"",""),
(NULL,1,"img/products/floor1/p8.png","泰国芭提雅Tiffany蒂芬妮人妖秀表演门票(可加订接送)",130,"",""),
(NULL,1,"img/products/floor1/p9.jpg","[毕业季立减]上海直飞沙巴6-7天自由行(仙本那蜜月水屋系列酒店+双人立减套餐+马穆迪岛+马努干岛双岛/美人鱼岛出海一日）游+可加购1日游套餐",1699,"",""),
(NULL,1,"img/products/floor1/p10.jpg","【网红综艺同款】【7月-9月】上海直飞缅甸5-8天自由行（走进大小S综艺拍摄地体验纯净海岸+综艺网红三地特色酒店可选+可选包车日游+可提前月预订热气球）",2899,"",""),
(NULL,1,"img/products/floor1/p11.jpg","上海/南京/杭州直飞泰国曼谷/清迈5-7往返机票（非廉价航空，直飞航班，含免费行李额）",1050,"",""),
(NULL,1,"img/products/floor1/p12.jpg","[拒签全退][暑假][国庆]杭州/上海直飞冲绳/大阪/东京/北海道4-6天往返含税机票(特别赠送冲绳单次签证+双人Wi-Fi/台+可升级冲绳3年多次签证+可代订酒店接送机)",1699,"",""),
(NULL,1,"img/products/floor1/p13.jpg","【8人黄金小团】苏格兰高地+天空岛+尼斯湖3日游(中文导游)-赠爱丁堡市区游",1710,"限时立减",""),
(NULL,1,"img/products/floor1/p14.jpg","法国普罗旺斯薰衣草圣十字湖大峡谷一日游 瓦伦索薰衣草+圣十字湖大峡谷 （阿维尼翁/艾克斯/尼斯 往返或异地上下 任您选择）",668,"",""),
(NULL,1,"img/products/floor1/p15.jpg","【出行必备】瑞士旅行通票Swiss Travel Pass电子票(欧铁官方一级代理)",746,"",""),
(NULL,1,"img/products/floor1/p16.jpg","【原生态象营】泰国清迈KerChor大象生态公园 (中文服务,体验象夫生活,照顾象宝宝)",160,"",""),
(NULL,1,"img/products/floor1/p17.jpg","[暑期/自由搭配来回程]上海直飞缅甸仰光单程含税机票（赠送仰光瑞光大金塔中文语音讲解）开口机票",999,"",""),
(NULL,1,"img/products/floor1/p18.jpg","[早定优惠][暑期热卖]上海直飞普吉岛5-7天自由行（部分套餐早定享优惠+多套航班任您选择+打卡网红酒店+全程自由安排+随时出发+可加购当地热门景点门票）",1499,"",""),
(NULL,1,"img/products/floor1/p19.png","[暑期][中秋][国庆]西安临潼华清宫长恨歌演出门票(景区取票+多票型可选+中区好位置+可选中A区/中B区+赠返程车)",298,"",""),
(NULL,1,"img/products/floor1/p20.jpg","[全年预售]北京直飞泰国曼谷/清迈6-7天往返含税机票（多航班可选+特价机票预售+可升级全程酒店）",1299,"",""),
(NULL,1,"img/products/floor1/p21.jpg","悉尼蓝山中文深度纯玩小团一日游（蓝山缆车+动物园+鲁拉小镇+可选午餐/落日游船/情人港网红餐厅晚餐+CBD免费接）",239,"",""),
(NULL,1,"img/products/floor1/p22.jpg","[亿点]泰国电话卡8天 4G无限流量 王权免税店联名上网卡（支持机场自取） ",19.99,"",""),
(NULL,1,"img/products/floor1/p23.jpg","日本交通充值卡 西瓜卡Suica（内含1500日币可用+500日币押金+赠日本机场打折券+自由行必备神器）",76,"",""),
(NULL,1,"img/products/floor1/p24.jpg","[上下午通用]北京故宫门票/联票(可选含钟表馆、珍宝馆）",20,"",""),
(NULL,2,"img/products/floor2/p1.jpg","[暑期/中秋/十一] 天津出发东京/大阪/札幌/名古屋4-7天往返机票（多航司可选）",1799,"机票","近期好货"),
(NULL,2,"img/products/floor2/p2.jpg","上海/宁波直飞曼谷6-8天往返含税机票（优质航空+行李托运+赠送首晚酒店）",1099,"机票","近期好货"),
(NULL,2,"img/products/floor2/p3.jpg","上海直飞德黑兰2-30天往返含税机票",4059,"机票","近期好货"),
(NULL,2,"img/products/floor2/p4.jpg","[花火大会预售]杭州/南京直飞日本东京/大阪/冲绳4-7天往返含税机票（双人赠wifi，可代办签证）",1850,"机票","近期好货"),
(NULL,2,"img/products/floor2/p5.jpg","[早定优惠][暑期热卖]上海直飞普吉岛5-7天自由行（部分套餐早定享优惠+多套航班任您选择+打卡网红酒店+全程自由安排+随时出发+可加购当地热门景点门票）",1499,"机+酒","近期好货"),
(NULL,2,"img/products/floor2/p6.jpg","[暑期]成都/重庆直飞清迈5-6天往返含税机票(包机航班+可代办签证+可自由搭配酒店自由行)",1399,"机票","近期好货"),
/*(NULL,2,"机票","酒店",0,"机+酒","近期好货"),*/
(NULL,2,"img/products/floor2/p7.jpg","[暑期]北京直飞柬埔寨金边6-7天往返含税机票（国航直飞/23KG行李额）",2699,"机票","新品汇聚"),
(NULL,2,"img/products/floor2/p8.jpg","[定制游]全国往返日本东京+大阪花火大会7日游（花火大会+镰仓高校+长谷寺+六本木丘展望台）",8999,"机+酒","新品汇聚"),
(NULL,2,"img/products/floor2/p9.gif","【含暑期】天津直飞缅甸曼德勒6-7天跟团游【探索婆娑净土】(全程0自费+乌本桥日落+十大日出塔林日出+佛教之国+多日期多线路任选)",999,"跟团游","新品汇聚"),
(NULL,2,"img/products/floor2/p10.jpg","【上海领区/顺丰包邮】日本个人旅游签证（单次/3年/5年）",55,"签证","新品汇聚"),
(NULL,2,"img/products/floor2/p11.jpg","[07月09日]星梦邮轮探索梦号天津往返长崎+鹿儿岛市6天5晚邮轮之旅",2188,"游轮","新品汇聚"),
(NULL,2,"img/products/floor2/p12.jpg","[暑期]济南/青岛/烟台返马来西亚仙本那 5-6天半自助游（纯玩丨敦沙卡兰海洋公园、 卡帕莱、潜水漫步/网红浮潜丨含一天自由时间 丨DIY纯玩 丨含电话卡、可升级深潜/蜜月/亲子的海岛之旅）",1000,"半自助游","新品汇聚"),
/*(NULL,2,"机票","酒店",0,"机+酒","新品汇聚"),*/
(NULL,2,"img/products/floor2/p13.jpg","【暑假】上海/杭州直飞塞班岛5-6天自由行(免签海岛/北部环岛/军舰(不含餐)/丛林探险+导服费+已含1550税费)",3590,"机+酒","好货值得买"),
(NULL,2,"img/products/floor2/p14.gif","香港直飞斐济8天往返含税机票（斐济航空，23KG托运，可配全国联运，超值机票）",4599,"机票","好货值得买"),
(NULL,2,"img/products/floor2/p15.jpg","[拒签全退][暑假][国庆]杭州/上海直飞冲绳/大阪/东京/北海道4-6天往返含税机票(特别赠送冲绳单次签证+双人Wi-Fi/台+可升级冲绳3年多次签证+可代订酒店接送机)",1699,"机票","好货值得买"),
(NULL,2,"img/products/floor2/p16.jpg","重庆往返沙巴6天4晚自由行(多酒店可升级/可延长回程时间/赠接送机+电话卡+赠旅游意外险)",2999,"机+酒","好货值得买"),
(NULL,2,"img/products/floor2/p17.jpg","[暑期热卖]上海直飞普吉+曼谷连线/普吉+清迈连线8天往返自由行(可选曼谷+芭提雅7天5晚套餐/加购回程行李额/可购买当地热门景点门票)",1799,"机+酒","好货值得买"),
(NULL,2,"img/products/floor2/p18.jpg","上海直飞日本东京/大阪/北海道/冲绳/福冈4-6天往返含税机票",2399,"机票","好货值得买"),
(NULL,2,"img/products/floor2/p19.jpg","[6月-10月]上海直飞大阪/名古屋/高松（四国香川）/北海道/佐贺（九州）/茨城（东京）5-7天往返含税日本机票(含当地交通卡/景点门票/DIY制作+全程自由安排+随时出发+可加购当地热门景点门票）",1299,"机票","假期出行"),
(NULL,2,"img/products/floor2/p20.jpg","【夏季赏花限定】上海直飞北海道札幌5天4晚日本自由行(可选一价全含ClubMed度假村/狸小路商业街/地铁站附近酒店)亲子系列",2599,"机+酒","假期出行"),
(NULL,2,"img/products/floor2/p21.jpg","上海直飞东京/大阪/名古屋/冲绳/札幌/福冈2-30天往返含税机票",2499,"机票","假期出行"),
(NULL,2,"img/products/floor2/p22.gif","[定制游]全国出发摩洛哥12天自由行（摩洛哥免签+摩洛哥探秘撒哈拉包车行程+梅尔祖卡沙漠安排特色帐篷露营+卡萨布兰卡/蓝色小镇/菲斯古城/撒哈拉沙漠+赠电话卡+赠路书全攻略+全国联运）",13800,"机+酒","假期出行"),
(NULL,2,"img/products/floor2/p23.gif","[09月28日]歌诗达邮轮大西洋号深圳往返马尼拉+苏比克6天5晚邮轮之旅",3249,"游轮","假期出行"),
(NULL,2,"img/products/floor2/p24.jpg","[08月18日]星梦邮轮探索梦号天津往返日本下关+长崎6天5晚邮轮之旅",2699,"游轮","假期出行"),
(NULL,2,"img/products/floor2/p25.gif","[暑期][花火大会预售]上海/南京/杭州直飞日本东京/大阪/冲绳/福冈/名古屋/阪东连线4-7天往返含税机票（双人赠wifi，可代订签证 ，可加订大阪/东京优惠酒店）",2050,"机票","机票优惠"),
(NULL,2,"img/products/floor2/p26.jpg","天津往返东京/大阪/名古屋/冲绳/札幌4-7天含税机票（大阪赠机场免税店电子折扣券/天津航空/日本航空/中国航空/A点进B点出+299得3年多次签证）",999,"机票","机票优惠"),
(NULL,2,"img/products/floor2/p27.jpg","上海/杭州直飞东京/大阪5-7天往返含税机票（两个人预定可赠送旅游意外险+可代订签证，酒店、定制行程）",2598,"机票","机票优惠"),
(NULL,2,"img/products/floor2/p28.jpg","[暑期]广州直飞缅甸仰光6天往返含税机票（南航正点航班+探秘万塔之国+缅甸自由行+多日期选择）",1799,"机票","机票优惠"),
(NULL,2,"img/products/floor2/p29.jpg","北京往返台北/台北进高雄出/高雄3-30天往返含税机票(可配联运，含行李额，五星航空公司)",2288,"机票","机票优惠"),
(NULL,2,"img/products/floor2/p30.gif","[花火大会预售]北京/天津直飞日本东京/大阪/冲绳/札幌/福冈4-7天往返含税机票（双人送wifi，可代订签证， 可订大阪心斋桥公寓）",2050,"机票","机票优惠"),
(NULL,2,"img/products/floor2/p31.jpg","[暑期]成都/重庆直飞泰国苏梅岛5-7天往返含税机票（可升级机酒自由行+搭配酒店送电话流量卡）",1750,"机票","热门海岛"),
(NULL,2,"img/products/floor2/p32.jpg","上海/南京/无锡/合肥往返马来西亚沙巴+仙本那6-7天自由行（海风拂面·多地出发+DIY行程设计+玩点新鲜的+高度自由+不走寻常路+享受你的假期）",4180,"机+酒","热门海岛"),
(NULL,2,"img/products/floor2/p33.jpg","全国多地直飞马尔代夫阿玛瑞岛6-7天自由行(免费珊瑚礁浮潜之旅/含三餐/饮和水无限量供/免费WiFi/免费浮潜设备)",12229,"机+酒","热门海岛"),
(NULL,2,"img/products/floor2/p34.jpg","北京出发巴厘岛7天5晚自由行（漂浮早餐/花瓣泳池/网红旅拍/萌娃亲子野生动物园酒店+赠接送机+金巴兰四季度假村下午茶）",2299,"机+酒","热门海岛"),
(NULL,2,"img/products/floor2/p35.jpg","上海/杭州直飞曼谷/普吉岛/清迈/甲米3-15天往返含税机票（赠送首晚住宿+行李托运+更多套餐可以选择）",1350,"机票","热门海岛"),
(NULL,2,"img/products/floor2/p36.jpg","[定制游]全国出发巴厘岛5-8天定制自由行（Ins网红风巴厘岛+实地考察巴厘岛美女客服+从此出行不迷茫）",7599,"机+酒","热门海岛"),
(NULL,2,"img/products/floor2/p37.jpg","【暑期】全国各地往返马尔代夫库拉玛提岛/K岛6-7天自由行（可升级一价全包+醉美拖尾沙滩+可申请蜜月套餐）",11199,"机+酒","甩尾"),
(NULL,2,"img/products/floor2/p38.jpg","[暑期]杭州直飞沙巴5天4晚自由行(香格里拉/麦哲伦等高档豪华酒店任选升级+含行李托运+代办签证+赠接送机/电话卡/旅意险)",4680,"机+酒","甩尾"),
(NULL,2,"img/products/floor2/p39.jpg","[全年预售]北京直飞泰国曼谷/清迈6-7天往返含税机票（多航班可选+特价机票预售+可升级全程酒店）",1299,"机票","甩尾"),
(NULL,2,"img/products/floor2/p40.jpg","【网红综艺同款】【7月-9月】上海直飞缅甸5-8天自由行（走进大小S综艺拍摄地体验纯净海岸+综艺网红三地特色酒店可选+可选包车日游+可提前月预订热气球）【北京领区/拒签全退】日本单次/多次个人旅游签证（可简化,可加急）",2899,"机+酒","甩尾"),
(NULL,2,"img/products/floor2/p41.jpg","【北京领区/拒签全退】日本单次/多次个人旅游签证（可简化,可加急）",60,"签证","甩尾"),
(NULL,2,"img/products/floor2/p42.jpg","武汉直飞柬埔寨西哈努克港8天往返含税机票（可定单程）",950,"机票","甩尾"),

(NULL,3,"img/products/floor3/p1.jpg","[上下午通用]北京故宫门票/联票(可选含钟表馆、珍宝馆）",20,"城市玩乐","国内"),
(NULL,3,"img/products/floor3/p2.jpg","【北京出发】北京故宫避暑半日游·秘制玩法·6人小团·深度趣味讲解·神秘全景俯瞰",188,"","国内"),
(NULL,3,"img/products/floor3/p3.jpg","青海湖3日游·小环线环湖·风靡欧美4+2玩法·单车旅行·优选酒店.6人VIP团",50,"","国内"),
(NULL,3,"img/products/floor3/p4.jpg","新青甘大环线·青海甘肃7日游6·人小团·别克商务车·删掉鸡肋点·青海湖住1晚",1000,"","国内"),
(NULL,3,"img/products/floor3/p5.jpg","青海湖+祁连+张掖5日游·6人小团·拒绝赶路·暖心好评·7座商务车·TOP5酒店·茶 卡体验·青甘大环线",500,"","国内"),
(NULL,3,"img/products/floor3/p6.jpg","北京恭王府花园电子票+电子导览",25,"","国内"),
(NULL,3,"img/products/floor3/p7.jpg","日本JR北海道hokkaido rail pass周游券(3/4/5/7日可选)",1018,"城市玩乐","日本"),
(NULL,3,"img/products/floor3/p8.jpg","【打卡必玩】日本东京迪斯尼乐园/迪士尼海洋1日实体票/电子票",299,"","日本"),
(NULL,3,"img/products/floor3/p9.jpg","日本关西地区JR Kansai WIDE Area Pass广域铁路周游(5日券,顺丰包邮)",555,"","日本"),
(NULL,3,"img/products/floor3/p10.jpg","日本随身WiFi4G网络不限流量（全国各地自取）",7.9,"","日本"),
(NULL,3,"img/products/floor3/p11.jpg","【日本】【无限4G流量】漫游超人随身WIFI 可订明日",8,"","日本"),
(NULL,3,"img/products/floor3/p12.jpg","【打卡必玩】日本大阪环球影城入园电子票",485,"","日本"),
(NULL,3,"img/products/floor3/p13.jpg","【原生态象营】泰国清迈KerChor大象生态公园 (中文服务,体验象夫生活,照顾象宝宝)",160,"城市玩乐","泰国"),
(NULL,3,"img/products/floor3/p14.jpg","泰国普吉珊瑚岛+蜜月岛豪华双体帆船寻海豚海钓之旅(中文导游)",375,"","泰国"),
(NULL,3,"img/products/floor3/p15.jpg","【专车接送】曼谷深度一日游 纯玩美功铁道+丹嫩 安帕瓦水上市场 可乘坐手划船+长尾船",145,"","泰国"),
(NULL,3,"img/products/floor3/p16.jpg","【潜水教练+中文导游】普吉岛皇帝岛+珊瑚岛双体帆船日落一日游 私人沙滩+自助午餐 【全岛接送+人身保险】",699,"","泰国"),
(NULL,3,"img/products/floor3/p17.jpg","泰国曼谷/芭堤雅出发长臂猿丛林飞跃（Flight of the Gibbon）",260,"","泰国"),
(NULL,3,"img/products/floor3/p18.jpg","【酒店接送/中文导游】泰国 曼谷美功铁道市场一日游【丹嫩沙朵水上市场/安帕瓦水上市场/大皇宫可选】",236,"","泰国"),
(NULL,3,"img/products/floor3/p19.jpg","瑞士旅行通票Swiss Travel Pass纸质票(欧铁官方一级代理，国内包邮)",746,"欧铁通票","瑞士"),
(NULL,3,"img/products/floor3/p20.jpg","瑞士少女峰一日游(卢塞恩出发)",1419,"","瑞士"),
(NULL,3,"img/products/floor3/p21.jpg","【旋转缆车】瑞士铁力士峰一日游(苏黎世往返)",689,"","瑞士"),
(NULL,3,"img/products/floor3/p22.jpg","瑞士半价卡Swiss Half Fare Card(欧铁官方一级代理，半价登少女峰)",985,"","瑞士"),
(NULL,3,"img/products/floor3/p23.jpg","瑞士 山峦皇后瑞吉峰 卢塞恩老城一日游 (苏黎世往返+齿轮火车+游船)",885,"","瑞士"),
(NULL,3,"img/products/floor3/p24.jpg","【经典日游】瑞士因特拉肯+格林德尔瓦尔德一日游(苏黎世往返)",456,"","瑞士"),
(NULL,3,"img/products/floor3/p25.jpg","【梦幻童话世界】香港迪士尼乐园一日/ 两日门票(可定今日+无需打印)",92,"城市玩乐","香港"),
(NULL,3,"img/products/floor3/p26.jpg","【绝美风景】香港昂坪360往返缆车票(电子换票证)",140,"","香港"),
(NULL,3,"img/products/floor3/p27.jpg","【赠送往返穿梭巴士】香港太平山杜莎夫人蜡像馆(无需打印+可定今日)",200,"","香港"),
(NULL,3,"img/products/floor3/p28.jpg","香港海洋公园电子门票 成人/儿童门票（快速出票，含园内缆车）",363,"","香港"),
(NULL,3,"img/products/floor3/p29.jpg","香港迪士尼乐园2日电子门票（快速入园，部分门票赠商品券，可选单门票/多人套票/门票餐券套票）",454,"","香港"),
(NULL,3,"img/products/floor3/p30.jpg","【可订当日】港澳台通用4GWIFI无限流量租赁（全国多地取还）",17.9,"","香港"),
(NULL,3,"img/products/floor3/p31.jpg","【冰雪奇缘】新西兰福克斯冰川直升机徒步/攀冰体验/峡谷徒步",2002,"城市玩乐","新西兰"),
(NULL,3,"img/products/floor3/p32.jpg","【精灵冒险】新西兰霍比特人电影拍摄地+怀托莫萤火虫洞一日游(奥克兰往返）",1495,"","新西兰"),
(NULL,3,"img/products/floor3/p33.jpg","【冲上云霄】新西兰瓦纳卡镇飞机训练营自驾体验",309,"","新西兰"),
(NULL,3,"img/products/floor3/p34.jpg","【特别推荐·会呼吸的龙虾】新西兰凯库拉2小时海钓之旅",309,"","新西兰"),
(NULL,3,"img/products/floor3/p35.jpg","【蹦极发源地】新西兰皇后镇卡瓦劳大桥蹦极 Kawarau Bungy多时间可选",749,"","新西兰"),
(NULL,3,"img/products/floor3/p36.jpg","新西兰皇后镇卡德罗纳Cardrona雪场滑雪一日游（一价全包+皇后镇/瓦纳卡接送+无需滑雪经验）",1080,"","新西兰"),
(NULL,3,"img/products/floor3/p37.jpg","【冲上云霄】--墨尔本学开飞机体验之旅 （飞满30/60分钟+中文教练）",824,"城市玩乐","澳大利亚"),
(NULL,3,"img/products/floor3/p38.jpg","【墨尔本两大必去景点】水族馆+尤利卡88层观景台门票",182,"","澳大利亚"),
(NULL,3,"img/products/floor3/p39.jpg","【悉尼歌剧院深度体验】澳大利亚悉尼歌剧院30分钟/1小时导览",123,"","澳大利亚"),
(NULL,3,"img/products/floor3/p40.jpg","悉尼蓝山中文深度纯玩小团一日游（蓝山缆车+动物园+鲁拉小镇+可选午餐/落日游船/情人港网红餐厅晚餐+CBD免费接）",239,"","澳大利亚"),
(NULL,3,"img/products/floor3/p41.jpg","澳大利亚阿德莱德袋鼠岛渡轮票",105,"","澳大利亚"),
(NULL,3,"img/products/floor3/p42.jpg","【六星餐厅】黄金海岸 范思哲宫殿酒店（海鲜自助晚餐/精美下午茶）",128,"","澳大利亚"),
(NULL,3,"img/products/floor3/p43.jpg","柬埔寨 暹粒 吴哥窟【吴哥王朝】大型演出门票（商家直销+酒店接送+快速出单+24小时中文客服）",232,"城市玩乐","柬埔寨"),
(NULL,3,"img/products/floor3/p44.jpg","【可订当日/快速出票/中文客服/可选接送】柬埔寨 暹粒吴哥窟《吴哥的微笑》演出门票",85,"","柬埔寨"),
(NULL,3,"img/products/floor3/p45.jpg","柬埔寨暹粒吴哥专车接送机服务（24小时接送机+丰富舒适车型+专业旅游车队）",89,"","柬埔寨"),
(NULL,3,"img/products/floor3/p46.jpg","尚路优享柬埔寨暹粒吴哥窟1日专业中文导游（完美中文景区讲解+不推自费购物）",450,"","柬埔寨"),
(NULL,3,"img/products/floor3/p47.jpg","【中文服务】柬埔寨暹粒崩密列+洞里萨湖+空邦鲁浮村一日游 (包含所有门票+4种午餐选择+赠送椰子竹筒饭+纯玩零自费无购物)",245,"","柬埔寨"),
(NULL,3,"img/products/floor3/p48.jpg","柬埔寨吴哥窟 中文语音电子导游（热门景点全覆盖+赠吴哥博物馆讲解+不限时使用）",15,"","柬埔寨");